import { GameConfig, GameId } from "@/types";
import {
  FaAdjust,
  FaBug,
  FaCamera,
  FaCircleNotch,
  FaCrop,
  FaDice,
  FaExpand,
  FaExclamationTriangle,
  FaEye,
  FaEyeDropper,
  FaFilm,
  FaFont,
  FaHandPointer,
  FaHashtag,
  FaImage,
  FaBold,
  FaPalette,
  FaPaintBrush,
  FaQuestionCircle,
  FaRulerCombined,
  FaShapes,
  FaSlidersH,
  FaSun,
  FaSwatchbook,
  FaTemperatureHigh,
  FaThLarge,
  FaTextHeight,
  FaUniversalAccess,
} from "react-icons/fa";

export const GAMES: Record<GameId, GameConfig> = {
  "color-compare": {
    id: "color-compare",
    name: "Сравни цвета",
    description: "Определи, какой цвет ярче, темнее или насыщеннее",
    icon: FaAdjust,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "font-size": {
    id: "font-size",
    name: "Размер шрифта",
    description: "Угадай размер шрифта в пикселях",
    icon: FaTextHeight,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "font-weight": {
    id: "font-weight",
    name: "Толщина шрифта",
    description: "Выбери самый лёгкий или самый жирный вес",
    icon: FaBold,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  "guess-font": {
    id: "guess-font",
    name: "Угадай шрифт",
    description: "Определи название шрифта",
    icon: FaFont,
    timeLimit: 60,
    pointsPerCorrect: 150,
  },
  "color-params": {
    id: "color-params",
    name: "Параметры цвета",
    description: "Сравни HSL параметры цветов",
    icon: FaSlidersH,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "color-temperature": {
    id: "color-temperature",
    name: "Температура цвета",
    description: "Определи тёплый или холодный оттенок",
    icon: FaTemperatureHigh,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  accessibility: {
    id: "accessibility",
    name: "Доступность",
    description: "Определи читаемость текста по WCAG",
    icon: FaUniversalAccess,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  "palette-error": {
    id: "palette-error",
    name: "Ошибка в палитре",
    description: "Найди цвет, который выбивается из палитры",
    icon: FaSwatchbook,
    timeLimit: 45,
    pointsPerCorrect: 150,
  },
  "size-sequence": {
    id: "size-sequence",
    name: "Типографская шкала",
    description: "Найди ошибку в последовательности размеров",
    icon: FaRulerCombined,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  complementary: {
    id: "complementary",
    name: "Дополнительный цвет",
    description: "Выбери комплементарный или split-комплемент",
    icon: FaPalette,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "guess-hex": {
    id: "guess-hex",
    name: "Угадай HEX",
    description: "Определи HEX-код цвета",
    icon: FaHashtag,
    timeLimit: 60,
    pointsPerCorrect: 200,
  },
  "guess-params": {
    id: "guess-params",
    name: "Угадай HSL",
    description: "Определи параметры H, S, L цвета",
    icon: FaEyeDropper,
    timeLimit: 60,
    pointsPerCorrect: 150,
  },
  quiz: {
    id: "quiz",
    name: "Квиз",
    description: "Тест по теории цвета и типографики",
    icon: FaQuestionCircle,
    timeLimit: 90,
    pointsPerCorrect: 100,
  },
  "theme-analog": {
    id: "theme-analog",
    name: "Тёмная/Светлая тема",
    description: "Подбери аналог цвета для другой темы",
    icon: FaSun,
    timeLimit: 45,
    pointsPerCorrect: 150,
  },
  "artist-guess": {
    id: "artist-guess",
    name: "Угадай художника",
    description: "Определи автора по изображению",
    icon: FaPaintBrush,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "style-guess": {
    id: "style-guess",
    name: "Угадай стиль",
    description: "Определи художественный стиль",
    icon: FaShapes,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "image-size": {
    id: "image-size",
    name: "Размер изображения",
    description: "Оцени размер кадра на глаз",
    icon: FaExpand,
    timeLimit: 60,
    pointsPerCorrect: 120,
  },
  "image-format": {
    id: "image-format",
    name: "Формат кадра",
    description: "Определи формат изображения",
    icon: FaCrop,
    timeLimit: 60,
    pointsPerCorrect: 120,
  },
  "color-eye": {
    id: "color-eye",
    name: "Цвет на глаз",
    description: "Подбери оттенок по фото",
    icon: FaEye,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "color-wheel": {
    id: "color-wheel",
    name: "Цветовой круг",
    description: "Найди комплементарный или аналоговый цвет",
    icon: FaCircleNotch,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "film-type": {
    id: "film-type",
    name: "Тип плёнки",
    description: "Определи плёнку по характеру кадра",
    icon: FaFilm,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "composition-technique": {
    id: "composition-technique",
    name: "Композиция",
    description: "Узнай композиционный приём",
    icon: FaThLarge,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "focal-length": {
    id: "focal-length",
    name: "Фокусное расстояние",
    description: "Определи фокус по фото",
    icon: FaCamera,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "wcag-issue": {
    id: "wcag-issue",
    name: "Проблема WCAG",
    description: "Найди ошибку доступности в макете",
    icon: FaExclamationTriangle,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "button-color": {
    id: "button-color",
    name: "Цвет кнопки",
    description: "Подбери контрастный цвет кнопки",
    icon: FaHandPointer,
    timeLimit: 60,
    pointsPerCorrect: 120,
  },
  "font-size-choice": {
    id: "font-size-choice",
    name: "Размер шрифта UI",
    description: "Подбери размер текста для интерфейса",
    icon: FaTextHeight,
    timeLimit: 60,
    pointsPerCorrect: 120,
  },
  "layout-error": {
    id: "layout-error",
    name: "Ошибка вёрстки",
    description: "Найди проблемное место в макете",
    icon: FaBug,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "palette-from-photo": {
    id: "palette-from-photo",
    name: "Палитра из фото",
    description: "Выбери подходящую палитру",
    icon: FaImage,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "long-test": {
    id: "long-test",
    name: "Длинный тест",
    description: "Смешанный раунд с вопросами из разных игр",
    icon: FaDice,
    timeLimit: 300,
    pointsPerCorrect: 120,
  },
};

export const GAME_ORDER: GameId[] = [
  "color-compare",
  "font-size",
  "font-weight",
  "guess-font",
  "color-params",
  "color-temperature",
  "accessibility",
  "palette-error",
  "size-sequence",
  "complementary",
  "guess-hex",
  "guess-params",
  "quiz",
  "theme-analog",
  "artist-guess",
  "style-guess",
  "image-size",
  "image-format",
  "color-eye",
  "color-wheel",
  "film-type",
  "composition-technique",
  "focal-length",
  "wcag-issue",
  "button-color",
  "font-size-choice",
  "layout-error",
  "palette-from-photo",
];
