import { GameConfig, GameId } from "@/types";
import {
  FaAdjust,
  FaBold,
  FaBug,
  FaCamera,
  FaCircleNotch,
  FaCrop,
  FaDice,
  FaExclamationTriangle,
  FaExpand,
  FaEye,
  FaEyeDropper,
  FaFilm,
  FaFont,
  FaHandPointer,
  FaHashtag,
  FaImage,
  FaPaintBrush,
  FaPalette,
  FaQuestionCircle,
  FaRulerCombined,
  FaShapes,
  FaSlidersH,
  FaSun,
  FaSwatchbook,
  FaTemperatureHigh,
  FaTextHeight,
  FaThLarge,
  FaUniversalAccess,
} from "react-icons/fa";

export const GAMES: Record<GameId, GameConfig> = {
  "color-compare": {
    id: "color-compare",
    name: "Сравнить цвета",
    description: "Определить, какой цвет ярче, темнее или насыщеннее",
    tags: ["color", "design"],
    icon: FaAdjust,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "font-size": {
    id: "font-size",
    name: "Размер шрифта",
    description: "Угадать размер шрифта в пикселях",
    tags: ["typography", "interface"],
    icon: FaTextHeight,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "font-weight": {
    id: "font-weight",
    name: "Толщина шрифта",
    description: "Выбрать самый лёгкий или самый жирный вес",
    tags: ["typography", "interface"],
    icon: FaBold,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  "guess-font": {
    id: "guess-font",
    name: "Угадать шрифт",
    description: "Определить название шрифта",
    tags: ["typography", "design"],
    icon: FaFont,
    timeLimit: 60,
    pointsPerCorrect: 150,
  },
  "color-params": {
    id: "color-params",
    name: "Параметры цвета",
    description: "Сравнить HSL параметры цветов",
    tags: ["color", "design"],
    icon: FaSlidersH,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "color-temperature": {
    id: "color-temperature",
    name: "Температура цвета",
    description: "Определить тёплый или холодный оттенок",
    tags: ["color", "design"],
    icon: FaTemperatureHigh,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  accessibility: {
    id: "accessibility",
    name: "Доступность",
    description: "Определить читаемость текста по WCAG",
    tags: ["accessibility", "interface"],
    icon: FaUniversalAccess,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  "palette-error": {
    id: "palette-error",
    name: "Ошибка в палитре",
    description: "Найти цвет, который выбивается из палитры",
    tags: ["color", "design"],
    icon: FaSwatchbook,
    timeLimit: 45,
    pointsPerCorrect: 150,
  },
  "size-sequence": {
    id: "size-sequence",
    name: "Типографская шкала",
    description: "Найти ошибку в последовательности размеров",
    tags: ["typography", "layout"],
    icon: FaRulerCombined,
    timeLimit: 45,
    pointsPerCorrect: 120,
  },
  complementary: {
    id: "complementary",
    name: "Дополнительный цвет",
    description: "Выбрать комплементарный или split-комплемент",
    tags: ["color", "theory"],
    icon: FaPalette,
    timeLimit: 45,
    pointsPerCorrect: 100,
  },
  "guess-hex": {
    id: "guess-hex",
    name: "Угадать HEX",
    description: "Определить HEX-код цвета",
    tags: ["color", "theory"],
    icon: FaHashtag,
    timeLimit: 60,
    pointsPerCorrect: 200,
  },
  "guess-params": {
    id: "guess-params",
    name: "Угадать HSL",
    description: "Определить параметры H, S, L цвета",
    tags: ["color", "theory"],
    icon: FaEyeDropper,
    timeLimit: 60,
    pointsPerCorrect: 150,
  },
  quiz: {
    id: "quiz",
    name: "Квиз",
    description: "Тест по теории цвета и типографики",
    tags: ["theory", "design"],
    icon: FaQuestionCircle,
    timeLimit: 90,
    pointsPerCorrect: 100,
  },
  "theme-analog": {
    id: "theme-analog",
    name: "Тёмная/Светлая тема",
    description: "Подобрать аналог цвета для другой темы",
    tags: ["color", "interface"],
    icon: FaSun,
    timeLimit: 45,
    pointsPerCorrect: 150,
  },
  "artist-guess": {
    id: "artist-guess",
    name: "Угадать художника",
    description: "Определить автора по изображению",
    tags: ["photo", "design"],
    icon: FaPaintBrush,
    timeLimit: 60,
    pointsPerCorrect: 140,
    disabled: true,
  },
  "style-guess": {
    id: "style-guess",
    name: "Угадать стиль",
    description: "Определить художественный стиль",
    tags: ["photo", "design"],
    icon: FaShapes,
    timeLimit: 60,
    pointsPerCorrect: 140,
    disabled: true,
  },
  "image-size": {
    id: "image-size",
    name: "Размер изображения",
    description: "Оценить размер кадра на глаз",
    tags: ["photo", "interface"],
    icon: FaExpand,
    timeLimit: 60,
    pointsPerCorrect: 120,
    disabled: true,
  },
  "image-format": {
    id: "image-format",
    name: "Формат кадра",
    description: "Определить формат изображения",
    tags: ["photo", "layout"],
    icon: FaCrop,
    timeLimit: 60,
    pointsPerCorrect: 120,
    disabled: true,
  },
  "color-eye": {
    id: "color-eye",
    name: "Цвет по образцу",
    description: "Подобрать оттенок по образцу",
    tags: ["color", "theory"],
    icon: FaEye,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "color-wheel": {
    id: "color-wheel",
    name: "Цветовой круг",
    description: "Найти комплементарный или аналоговый цвет",
    tags: ["color", "theory"],
    icon: FaCircleNotch,
    timeLimit: 60,
    pointsPerCorrect: 130,
    disabled: true,
  },
  "film-type": {
    id: "film-type",
    name: "Профиль плёнки",
    description: "Определить профиль по карте цветов",
    tags: ["photo", "theory"],
    icon: FaFilm,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "composition-technique": {
    id: "composition-technique",
    name: "Композиция",
    description: "Определить приём по схеме",
    tags: ["photo", "layout"],
    icon: FaThLarge,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "focal-length": {
    id: "focal-length",
    name: "Фокусное расстояние",
    description: "Определить фокус по углу обзора",
    tags: ["photo", "theory"],
    icon: FaCamera,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "fov-angle": {
    id: "fov-angle",
    name: "Угол обзора",
    description: "Оценить угол обзора по схеме",
    tags: ["photo", "theory"],
    icon: FaCamera,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "wcag-issue": {
    id: "wcag-issue",
    name: "Проблема WCAG",
    description: "Найти ошибку доступности в макете",
    tags: ["accessibility", "interface"],
    icon: FaExclamationTriangle,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "button-color": {
    id: "button-color",
    name: "Цвет кнопки",
    description: "Подобрать контрастный цвет кнопки",
    tags: ["interface", "color"],
    icon: FaHandPointer,
    timeLimit: 60,
    pointsPerCorrect: 120,
  },
  "font-size-choice": {
    id: "font-size-choice",
    name: "Размер шрифта UI",
    description: "Подобрать размер текста для интерфейса",
    tags: ["interface", "typography"],
    icon: FaTextHeight,
    timeLimit: 60,
    pointsPerCorrect: 120,
  },
  "layout-error": {
    id: "layout-error",
    name: "Ошибка вёрстки",
    description: "Найти проблемное место в макете",
    tags: ["layout", "interface"],
    icon: FaBug,
    timeLimit: 60,
    pointsPerCorrect: 130,
  },
  "palette-from-photo": {
    id: "palette-from-photo",
    name: "Палитра по образцу",
    description: "Выбрать совпадающую палитру",
    tags: ["color", "design"],
    icon: FaImage,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "palette-lab": {
    id: "palette-lab",
    name: "Лаборатория палитр",
    description: "Сопоставить палитру с сгенерированной сценой",
    tags: ["color", "design"],
    icon: FaPalette,
    timeLimit: 60,
    pointsPerCorrect: 140,
  },
  "long-test": {
    id: "long-test",
    name: "Длинный тест",
    description: "Смешанный раунд с вопросами из разных игр",
    tags: ["theory", "design"],
    icon: FaDice,
    timeLimit: 300,
    pointsPerCorrect: 120,
  },
};

const ALL_GAME_ORDER: GameId[] = [
  "color-compare",
  "font-size",
  "font-weight",
  "guess-font",
  "color-params",
  "color-temperature",
  "accessibility",
  "palette-error",
  "size-sequence",
  "complementary",
  "guess-hex",
  "guess-params",
  "quiz",
  "theme-analog",
  "artist-guess",
  "style-guess",
  "image-size",
  "image-format",
  "color-eye",
  "color-wheel",
  "film-type",
  "composition-technique",
  "focal-length",
  "fov-angle",
  "wcag-issue",
  "button-color",
  "font-size-choice",
  "layout-error",
  "palette-from-photo",
  "palette-lab",
];

export const DISABLED_GAME_IDS = new Set<GameId>((Object.keys(GAMES) as GameId[]).filter((id) => GAMES[id].disabled));

export const GAME_ORDER: GameId[] = ALL_GAME_ORDER.filter((id) => !DISABLED_GAME_IDS.has(id));

export const normalizeGameOrder = (order: GameId[]): GameId[] => {
  const seen = new Set<GameId>();
  const filtered = order.filter((id) => {
    if (!GAME_ORDER.includes(id) || seen.has(id) || DISABLED_GAME_IDS.has(id)) return false;
    seen.add(id);
    return true;
  });
  const missing = GAME_ORDER.filter((id) => !seen.has(id));
  return [...filtered, ...missing];
};
