import { GameId } from "@/types";
import { Difficulty } from "@/utils/difficulty";
import { LocalizedText } from "@/utils/i18n";

export interface ImageQuizSource {
  label: string | LocalizedText;
  url?: string;
}

export interface ImageQuizOption {
  label: string | LocalizedText;
  color?: string;
  palette?: string[];
  size?: number;
}

export interface ImageQuizQuestion {
  id: string;
  prompt: string | LocalizedText;
  helper?: string | LocalizedText;
  explanation: string | LocalizedText;
  imageSrc: string;
  imageAlt: string | LocalizedText;
  imageSource?: ImageQuizSource;
  imageContainerClass?: string;
  imageFrameClass?: string;
  imageClass?: string;
  options: ImageQuizOption[];
  correctIndex: number;
  difficulty?: Difficulty;
}

export const IMAGE_QUIZ_IDS = [
  "artist-guess",
  "style-guess",
  "image-size",
  "image-format",
  "color-eye",
  "color-wheel",
  "film-type",
  "composition-technique",
  "focal-length",
  "wcag-issue",
  "button-color",
  "font-size-choice",
  "layout-error",
  "palette-from-photo",
] as const satisfies GameId[];

export type ImageQuizGameId = (typeof IMAGE_QUIZ_IDS)[number];

const commons = (file: string, width = 1200) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${width}`;

const sources = {
  commons: { label: { ru: "Wikimedia Commons", en: "Wikimedia Commons" }, url: "https://commons.wikimedia.org" },
  internal: { label: { ru: "Внутренний макет", en: "Internal mockup" } },
};

const text = (ru: string, en: string): LocalizedText => ({ ru, en });

export const IMAGE_QUIZ_DATA: Record<ImageQuizGameId, ImageQuizQuestion[]> = {
  "artist-guess": [
    {
      id: "artist-mona-lisa",
      prompt: text("Кто автор этой работы?", "Who is the author of this work?"),
      helper: text("Обрати внимание на эпоху и манеру письма.", "Pay attention to the era and manner of painting."),
      explanation: text(
        "«Мона Лиза» — работа Леонардо да Винчи эпохи Возрождения.",
        "The Mona Lisa is a Renaissance work by Leonardo da Vinci.",
      ),
      imageSrc: commons("Mona_Lisa.jpg"),
      imageAlt: text("Мона Лиза", "Mona Lisa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Леонардо да Винчи", "Leonardo da Vinci") },
        { label: text("Рафаэль", "Raphael") },
        { label: text("Сандро Боттичелли", "Sandro Botticelli") },
        { label: text("Рембрандт", "Rembrandt") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "artist-venus",
      prompt: text("Кто написал эту картину?", "Who painted this work?"),
      helper: text(
        "Обрати внимание на плавные линии и мифологический сюжет.",
        "Look for flowing lines and a mythological subject.",
      ),
      explanation: text("«Рождение Венеры» — Сандро Боттичелли.", "The Birth of Venus is by Sandro Botticelli."),
      imageSrc: commons("Birth_of_Venus_Botticelli.jpg"),
      imageAlt: text("Рождение Венеры", "The Birth of Venus"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Сандро Боттичелли", "Sandro Botticelli") },
        { label: text("Тициан", "Titian") },
        { label: text("Леонардо да Винчи", "Leonardo da Vinci") },
        { label: text("Рафаэль", "Raphael") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-monet",
      prompt: text("Определи художника по работе.", "Identify the artist from the work."),
      helper: text("Эта картина дала имя целому направлению.", "This painting gave a name to an entire movement."),
      explanation: text(
        "«Impression, soleil levant» — Клод Моне, основатель импрессионизма.",
        "Impression, Sunrise is by Claude Monet, founder of Impressionism.",
      ),
      imageSrc: commons("Claude_Monet,_Impression,_soleil_levant.jpg"),
      imageAlt: text("Impression, soleil levant", "Impression, Sunrise"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Клод Моне", "Claude Monet") },
        { label: text("Эдгар Дега", "Edgar Degas") },
        { label: text("Пьер-Огюст Ренуар", "Pierre-Auguste Renoir") },
        { label: text("Камиль Писсарро", "Camille Pissarro") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-wave",
      prompt: text("Кто автор этой гравюры?", "Who is the author of this print?"),
      helper: text("Гравюра с выразительными линиями и морской темой.", "A print with strong lines and a sea theme."),
      explanation: text(
        "«Большая волна в Канагаве» — Кацусика Хокусай.",
        "The Great Wave off Kanagawa is by Katsushika Hokusai.",
      ),
      imageSrc: commons("Great_Wave_off_Kanagawa.jpg"),
      imageAlt: text("Большая волна в Канагаве", "The Great Wave off Kanagawa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Кацусика Хокусай", "Katsushika Hokusai") },
        { label: text("Утагава Хиросигэ", "Utagawa Hiroshige") },
        { label: text("Китагава Утамаро", "Kitagawa Utamaro") },
        { label: text("Сэссю Тойо", "Sesshu Toyo") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-vermeer",
      prompt: text("Кто автор этого портрета?", "Who painted this portrait?"),
      helper: text("Нидерландская живопись XVII века.", "Dutch painting of the 17th century."),
      explanation: text(
        "«Девушка с жемчужной серёжкой» — Ян Вермеер.",
        "Girl with a Pearl Earring is by Johannes Vermeer.",
      ),
      imageSrc: commons("Girl_with_a_Pearl_Earring.jpg"),
      imageAlt: text("Девушка с жемчужной серёжкой", "Girl with a Pearl Earring"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Ян Вермеер", "Johannes Vermeer") },
        { label: text("Питер Пауль Рубенс", "Peter Paul Rubens") },
        { label: text("Рембрандт", "Rembrandt") },
        { label: text("Ян ван Эйк", "Jan van Eyck") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-bosch",
      prompt: text("Определи автора этой работы.", "Identify the author of this work."),
      helper: text(
        "Многофигурная аллегорическая сцена с множеством деталей.",
        "A multi-figure allegorical scene full of details.",
      ),
      explanation: text("«Сад земных наслаждений» — Иероним Босх.", "The Garden of Earthly Delights is by Hieronymus Bosch."),
      imageSrc: commons("Garden_of_Earthly_Delights.jpg"),
      imageAlt: text("Сад земных наслаждений", "The Garden of Earthly Delights"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Иероним Босх", "Hieronymus Bosch") },
        { label: text("Питер Брейгель", "Pieter Bruegel") },
        { label: text("Альбрехт Дюрер", "Albrecht Durer") },
        { label: text("Фра Беато Анджелико", "Fra Angelico") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
  ],
  "style-guess": [
    {
      id: "style-renaissance",
      prompt: text("Определи стиль по изображению.", "Identify the style from the image."),
      helper: text("Внимание к анатомии и светотени.", "Focus on anatomy and chiaroscuro."),
      explanation: text(
        "«Мона Лиза» относится к эпохе Высокого Возрождения.",
        "The Mona Lisa belongs to the High Renaissance.",
      ),
      imageSrc: commons("Mona_Lisa.jpg"),
      imageAlt: text("Мона Лиза", "Mona Lisa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Ренессанс", "Renaissance") },
        { label: text("Барокко", "Baroque") },
        { label: text("Кубизм", "Cubism") },
        { label: text("Сюрреализм", "Surrealism") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "style-impressionism",
      prompt: text("Какой это стиль?", "What style is this?"),
      helper: text("Размытые мазки, свет и воздух.", "Blurred strokes, light, and air."),
      explanation: text("Картина Моне стала символом импрессионизма.", "Monet's painting became a symbol of Impressionism."),
      imageSrc: commons("Claude_Monet,_Impression,_soleil_levant.jpg"),
      imageAlt: text("Impression, soleil levant", "Impression, Sunrise"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Импрессионизм", "Impressionism") },
        { label: text("Экспрессионизм", "Expressionism") },
        { label: text("Неоклассицизм", "Neoclassicism") },
        { label: text("Поп-арт", "Pop Art") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "style-ukiyo",
      prompt: text("Определи стиль гравюры.", "Identify the style of the print."),
      helper: text("Плоскостные формы и декоративный рисунок.", "Flat shapes and decorative linework."),
      explanation: text("Укиё-э — традиционная японская графика.", "Ukiyo-e is traditional Japanese printmaking."),
      imageSrc: commons("Great_Wave_off_Kanagawa.jpg"),
      imageAlt: text("Большая волна в Канагаве", "The Great Wave off Kanagawa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Укиё-э", "Ukiyo-e") },
        { label: text("Романтизм", "Romanticism") },
        { label: text("Реализм", "Realism") },
        { label: text("Барокко", "Baroque") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "style-early-renaissance",
      prompt: text("Выбери стиль картины.", "Choose the style of the painting."),
      helper: text("Мифологический сюжет и плавные линии.", "Mythological subject and flowing lines."),
      explanation: text(
        "«Рождение Венеры» — ранний итальянский Ренессанс.",
        "The Birth of Venus is Early Italian Renaissance.",
      ),
      imageSrc: commons("Birth_of_Venus_Botticelli.jpg"),
      imageAlt: text("Рождение Венеры", "The Birth of Venus"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Ранний Ренессанс", "Early Renaissance") },
        { label: text("Готика", "Gothic") },
        { label: text("Барокко", "Baroque") },
        { label: text("Рококо", "Rococo") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "style-baroque",
      prompt: text("Определи стиль по живописи.", "Identify the style from the painting."),
      helper: text("Драматическое освещение и пластика форм.", "Dramatic lighting and sculptural forms."),
      explanation: text(
        "Барокко характерно сильным светотеневым контрастом.",
        "Baroque is known for strong light–shadow contrast.",
      ),
      imageSrc: commons("Girl_with_a_Pearl_Earring.jpg"),
      imageAlt: text("Портрет", "Portrait"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Барокко", "Baroque") },
        { label: text("Кубизм", "Cubism") },
        { label: text("Футуризм", "Futurism") },
        { label: text("Сюрреализм", "Surrealism") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "style-northern-renaissance",
      prompt: text("Выбери стиль этой работы.", "Choose the style of this work."),
      helper: text("Сложная символика и аллегории.", "Complex symbolism and allegory."),
      explanation: text(
        "Северное Возрождение — характерная детализация и символизм.",
        "Northern Renaissance is known for detailed rendering and symbolism.",
      ),
      imageSrc: commons("Garden_of_Earthly_Delights.jpg"),
      imageAlt: text("Сад земных наслаждений", "The Garden of Earthly Delights"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Северное Возрождение", "Northern Renaissance") },
        { label: text("Романтизм", "Romanticism") },
        { label: text("Импрессионизм", "Impressionism") },
        { label: text("Поп-арт", "Pop Art") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
  ],
  "image-size": [
    {
      id: "size-280x180",
      prompt: "Какой размер изображения на экране?",
      helper: "Оцени рамку в пикселях.",
      explanation: "Кадр отображается как 280×180 px.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[280px] h-[180px]",
      imageClass: "object-cover",
      options: [
        { label: "280×180 px" },
        { label: "320×200 px" },
        { label: "240×160 px" },
        { label: "360×240 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-360x240",
      prompt: "Определи размер изображения.",
      helper: "Сравни визуальные пропорции.",
      explanation: "Кадр задан как 360×240 px.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Горный пейзаж",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[360px] h-[240px]",
      imageClass: "object-cover",
      options: [
        { label: "360×240 px" },
        { label: "320×200 px" },
        { label: "400×260 px" },
        { label: "280×180 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-320x200",
      prompt: "Определи размер кадра.",
      helper: "Сравни рамку с типовыми размерами.",
      explanation: "Кадр задан как 320×200 px.",
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: "Планета Земля",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[320px] h-[200px]",
      imageClass: "object-cover",
      options: [
        { label: "320×200 px" },
        { label: "280×180 px" },
        { label: "360×240 px" },
        { label: "400×260 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-240x160",
      prompt: "Какой размер изображения?",
      helper: "Сравни по масштабу с соседними вариантами.",
      explanation: "Кадр отображается как 240×160 px.",
      imageSrc: commons("Mountain view in Robson valley.jpg"),
      imageAlt: "Горный пейзаж",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[240px] h-[160px]",
      imageClass: "object-cover",
      options: [
        { label: "240×160 px" },
        { label: "280×180 px" },
        { label: "320×200 px" },
        { label: "200×140 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-300x200",
      prompt: "Определи размер кадра.",
      helper: "Смотри на пропорции и ширину.",
      explanation: "Кадр задан как 300×200 px.",
      imageSrc: commons("Beach, New Brighton, New Zealand 06.jpg"),
      imageAlt: "Пляж",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[300px] h-[200px]",
      imageClass: "object-cover",
      options: [
        { label: "300×200 px" },
        { label: "320×200 px" },
        { label: "280×180 px" },
        { label: "360×240 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-400x260",
      prompt: "Какой размер изображения на экране?",
      helper: "Оцени размеры рамки.",
      explanation: "Кадр отображается как 400×260 px.",
      imageSrc: commons("City Skyline from Above (Unsplash).jpg"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[400px] h-[260px]",
      imageClass: "object-cover",
      options: [
        { label: "400×260 px" },
        { label: "360×240 px" },
        { label: "420×280 px" },
        { label: "320×200 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-360x220",
      prompt: "Определи размер кадра.",
      helper: "Сравни ширину и высоту.",
      explanation: "Кадр задан как 360×220 px.",
      imageSrc: commons("River Cuckmere April 2018 01.jpg"),
      imageAlt: "Река",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[360px] h-[220px]",
      imageClass: "object-cover",
      options: [
        { label: "360×220 px" },
        { label: "360×240 px" },
        { label: "320×200 px" },
        { label: "400×260 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-420x280",
      prompt: "Какой размер изображения?",
      helper: "Оцени рамку и площадь.",
      explanation: "Кадр отображается как 420×280 px.",
      imageSrc: commons("Bridge Vittorio Emanuele II at sunset.jpg"),
      imageAlt: "Мост на закате",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[420px] h-[280px]",
      imageClass: "object-cover",
      options: [
        { label: "420×280 px" },
        { label: "400×260 px" },
        { label: "360×240 px" },
        { label: "320×200 px" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "size-260x180",
      prompt: "Определи размер изображения.",
      helper: "Смотри на рамку и пропорции.",
      explanation: "Кадр задан как 260×180 px.",
      imageSrc: commons("Forest road Slavne 2017 G8.jpg"),
      imageAlt: "Лесная дорога",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[260px] h-[180px]",
      imageClass: "object-cover",
      options: [
        { label: "260×180 px" },
        { label: "240×160 px" },
        { label: "280×180 px" },
        { label: "300×200 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-320x180",
      prompt: "Какой размер кадра?",
      helper: "Сравни ширину и высоту.",
      explanation: "Кадр отображается как 320×180 px.",
      imageSrc: commons("Night sky in the Alps - panoramio (3).jpg"),
      imageAlt: "Ночное небо",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[320px] h-[180px]",
      imageClass: "object-cover",
      options: [
        { label: "320×180 px" },
        { label: "320×200 px" },
        { label: "300×200 px" },
        { label: "360×220 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-300x220",
      prompt: "Определи размер изображения.",
      helper: "Оцени высоту относительно ширины.",
      explanation: "Кадр задан как 300×220 px.",
      imageSrc: commons("Lake Agnes im Banff National Park.jpg"),
      imageAlt: "Озеро",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[300px] h-[220px]",
      imageClass: "object-cover",
      options: [
        { label: "300×220 px" },
        { label: "320×200 px" },
        { label: "280×200 px" },
        { label: "360×240 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-280x200",
      prompt: "Какой размер кадра?",
      helper: "Оцени пропорции по высоте.",
      explanation: "Кадр отображается как 280×200 px.",
      imageSrc: commons("Beach - San Agustín.jpg"),
      imageAlt: "Пляж",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[280px] h-[200px]",
      imageClass: "object-cover",
      options: [
        { label: "280×200 px" },
        { label: "300×200 px" },
        { label: "260×180 px" },
        { label: "320×200 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-340x220",
      prompt: "Определи размер изображения на экране.",
      helper: "Сравни ширину с высотой.",
      explanation: "Кадр задан как 340×220 px.",
      imageSrc: commons("City Skyline from balcony.jpg"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[340px] h-[220px]",
      imageClass: "object-cover",
      options: [
        { label: "340×220 px" },
        { label: "360×220 px" },
        { label: "320×200 px" },
        { label: "300×200 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "image-format": [
    {
      id: "format-3-2",
      prompt: "Какой формат кадра?",
      helper: "Посмотри на отношение сторон.",
      explanation: "Кадр задан в формате 3:2.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Горный пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "3:2" },
        { label: "4:3" },
        { label: "16:9" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-4-3",
      prompt: "Определи формат изображения.",
      helper: "Присмотрись к рамке.",
      explanation: "Визуально это формат 4:3.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "4:3" },
        { label: "3:2" },
        { label: "1:1" },
        { label: "16:9" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-1-1",
      prompt: "Какой формат кадра?",
      helper: "Кадр выглядит квадратным.",
      explanation: "Формат 1:1 — квадрат.",
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: "Земля",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "1:1" },
        { label: "4:3" },
        { label: "3:2" },
        { label: "16:9" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-16-9",
      prompt: "Определи формат изображения.",
      helper: "Широкий кадр с низкой высотой.",
      explanation: "Это формат 16:9.",
      imageSrc: commons("City Skyline Urban Skyscrapers (Unsplash).jpg"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[16/9]",
      imageClass: "object-cover",
      options: [
        { label: "16:9" },
        { label: "3:2" },
        { label: "4:3" },
        { label: "2:1" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-2-1",
      prompt: "Какой формат кадра?",
      helper: "Очень широкий кадр.",
      explanation: "Формат 2:1 — панорамный.",
      imageSrc: commons("Bridge Vittorio Emanuele II at sunset.jpg"),
      imageAlt: "Мост на закате",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[2/1]",
      imageClass: "object-cover",
      options: [
        { label: "2:1" },
        { label: "16:9" },
        { label: "3:2" },
        { label: "4:3" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-5-4",
      prompt: "Определи формат изображения.",
      helper: "Кадр чуть выше, чем 4:3.",
      explanation: "Формат 5:4 — почти квадратный.",
      imageSrc: commons("Lake Agnes im Banff National Park.jpg"),
      imageAlt: "Озеро",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[5/4]",
      imageClass: "object-cover",
      options: [
        { label: "5:4" },
        { label: "4:3" },
        { label: "1:1" },
        { label: "3:2" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-3-4",
      prompt: "Какой формат кадра?",
      helper: "Кадр вертикальный.",
      explanation: "Формат 3:4 — портретный.",
      imageSrc: commons("Girl_with_a_Pearl_Earring.jpg"),
      imageAlt: "Портрет",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[3/4]",
      imageClass: "object-contain",
      options: [
        { label: "3:4" },
        { label: "2:3" },
        { label: "4:3" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-2-3",
      prompt: "Определи формат кадра.",
      helper: "Высота значительно больше ширины.",
      explanation: "Формат 2:3 — классический портрет.",
      imageSrc: commons("Mountains from Hatcher Pass (Alaska).jpg"),
      imageAlt: "Горы",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[2/3]",
      imageClass: "object-cover",
      options: [
        { label: "2:3" },
        { label: "3:4" },
        { label: "4:3" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-9-16",
      prompt: "Определи формат изображения.",
      helper: "Вертикальный кадр, как в мобильном.",
      explanation: "Это формат 9:16.",
      imageSrc: commons("Forest road Slavne 2017 G8.jpg"),
      imageAlt: "Лесная дорога",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[9/16]",
      imageClass: "object-cover",
      options: [
        { label: "9:16" },
        { label: "2:3" },
        { label: "3:4" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-21-9",
      prompt: "Какой формат кадра?",
      helper: "Очень широкий кадр, почти панорама.",
      explanation: "Формат 21:9 — ультраширокий.",
      imageSrc: commons("River Narmada from Maheshwar Fort.jpg"),
      imageAlt: "Река",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[21/9]",
      imageClass: "object-cover",
      options: [
        { label: "21:9" },
        { label: "16:9" },
        { label: "3:2" },
        { label: "2:1" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "format-4-5",
      prompt: "Определи формат изображения.",
      helper: "Высота немного больше ширины.",
      explanation: "Формат 4:5 часто используется в соцсетях.",
      imageSrc: commons("Beach - San Agustín.jpg"),
      imageAlt: "Пляж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[4/5]",
      imageClass: "object-cover",
      options: [
        { label: "4:5" },
        { label: "3:4" },
        { label: "2:3" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-3-1",
      prompt: "Определи формат кадра.",
      helper: "Очень широкий, почти баннер.",
      explanation: "Формат 3:1 — панорамный.",
      imageSrc: commons("City Skyline from Sidney Harbour.JPG"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/1]",
      imageClass: "object-cover",
      options: [
        { label: "3:1" },
        { label: "2:1" },
        { label: "16:9" },
        { label: "3:2" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "format-5-3",
      prompt: "Определи формат изображения.",
      helper: "Широкий кадр, но не панорама.",
      explanation: "Формат 5:3 — умеренно широкий.",
      imageSrc: commons("Desert varnish - Valley of Fire State Park.JPG"),
      imageAlt: "Пустыня",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[5/3]",
      imageClass: "object-cover",
      options: [
        { label: "5:3" },
        { label: "3:2" },
        { label: "16:9" },
        { label: "4:3" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
  ],
  "color-eye": [
    {
      id: "color-flower",
      prompt: "Какой цвет ближе всего к лепесткам?",
      helper: "Оцени доминирующий оттенок.",
      explanation: "Лепестки ближе к красно-коралловому оттенку.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Красный цветок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "#e24b4b", color: "#e24b4b" },
        { label: "#f2c94c", color: "#f2c94c" },
        { label: "#2d9cdb", color: "#2d9cdb" },
        { label: "#27ae60", color: "#27ae60" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-sky",
      prompt: "Какой оттенок ближе всего к небу?",
      helper: "Сравни холодные тона.",
      explanation: "Небо ближе к холодному синеватому оттенку.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Горный пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#4f7fbf", color: "#4f7fbf" },
        { label: "#5f9ea0", color: "#5f9ea0" },
        { label: "#7f8c8d", color: "#7f8c8d" },
        { label: "#6ab04c", color: "#6ab04c" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-earth",
      prompt: "Какой цвет ближе к океанам на фото?",
      helper: "Оцени глубину синего.",
      explanation: "Океаны ближе к насыщенному синему оттенку.",
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: "Земля из космоса",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "#1f5fbf", color: "#1f5fbf" },
        { label: "#3b82f6", color: "#3b82f6" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#94a3b8", color: "#94a3b8" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-sunset-amber",
      prompt: "Какой оттенок ближе всего к небу на закате?",
      helper: "Смотри на тёплые участки неба.",
      explanation: "Закат даёт янтарно-оранжевый оттенок.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Закат",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#8b5cf6", color: "#8b5cf6" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-ocean-teal",
      prompt: "Какой оттенок ближе к воде на снимке?",
      helper: "Оцени доминирующий сине-зелёный тон.",
      explanation: "Вода ближе к яркому бирюзово-синему.",
      imageSrc: commons("Ocean beach at low tide against the sun.jpg"),
      imageAlt: "Океан на закате",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#f97316", color: "#f97316" },
        { label: "#16a34a", color: "#16a34a" },
        { label: "#9ca3af", color: "#9ca3af" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-forest-green",
      prompt: "Какой оттенок ближе к листве в кадре?",
      helper: "Смотри на средние зелёные тона.",
      explanation: "Листва ближе к насыщенному зелёному.",
      imageSrc: commons(
        "Beech Forest (AU), Great Otway National Park, Beauchamp Falls -- 2019 -- 1271.jpg"
      ),
      imageAlt: "Лес",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#2f855a", color: "#2f855a" },
        { label: "#60a5fa", color: "#60a5fa" },
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#a855f7", color: "#a855f7" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-snow-cold",
      prompt: "Какой оттенок ближе всего к снегу?",
      helper: "Снег выглядит холодным и светлым.",
      explanation: "Снег ближе к холодному светло-серому.",
      imageSrc: commons("Snow Scene at Shipka Pass 1.JPG"),
      imageAlt: "Зимний пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#e5e7eb", color: "#e5e7eb" },
        { label: "#fef3c7", color: "#fef3c7" },
        { label: "#93c5fd", color: "#93c5fd" },
        { label: "#94a3b8", color: "#94a3b8" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-desert-sand",
      prompt: "Какой оттенок ближе к песку?",
      helper: "Смотри на тёплые землистые тона.",
      explanation: "Песок ближе к тёплому охристому.",
      imageSrc: commons("Acacia in Ein Khadra Desert Oasis 00 (87).jpg"),
      imageAlt: "Пустыня с акацией",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#d97706", color: "#d97706" },
        { label: "#3b82f6", color: "#3b82f6" },
        { label: "#16a34a", color: "#16a34a" },
        { label: "#64748b", color: "#64748b" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-flower-magenta",
      prompt: "Какой цвет ближе к лепесткам?",
      helper: "Учитывай насыщенный розовый оттенок.",
      explanation: "Лепестки ближе к насыщенному розово-магентовому.",
      imageSrc: commons(
        "Stargazer Lillies Lillium orientale 'Stargazer' Flower 2000px.jpg"
      ),
      imageAlt: "Лилии",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "#ec4899", color: "#ec4899" },
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#22c55e", color: "#22c55e" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-lake-turquoise",
      prompt: "Какой оттенок ближе к воде?",
      helper: "Вода выглядит холодной и бирюзовой.",
      explanation: "Оттенок воды ближе к бирюзовому.",
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: "Горное озеро",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#14b8a6", color: "#14b8a6" },
        { label: "#f97316", color: "#f97316" },
        { label: "#ef4444", color: "#ef4444" },
        { label: "#6b7280", color: "#6b7280" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-aurora-green",
      prompt: "Какой оттенок ближе всего к сиянию?",
      helper: "Смотри на основной цвет полярного сияния.",
      explanation: "Сияние ближе к яркому зелёному.",
      imageSrc: commons("Virmalised 15.09.2017 - Aurora Borealis 15.09.2017 copy.jpg"),
      imageAlt: "Полярное сияние",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#22c55e", color: "#22c55e" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#f97316", color: "#f97316" },
        { label: "#a855f7", color: "#a855f7" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-river-blue",
      prompt: "Какой оттенок ближе к воде в реке?",
      helper: "Смотри на холодные синие тона.",
      explanation: "Вода ближе к прохладному голубому.",
      imageSrc: commons("Rogue River Oregon USA.jpg"),
      imageAlt: "Река",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#38bdf8", color: "#38bdf8" },
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#9ca3af", color: "#9ca3af" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-sunset-pink",
      prompt: "Какой оттенок ближе к облакам на закате?",
      helper: "Смотри на розово-лиловые тона.",
      explanation: "Облака ближе к тёплому розовому.",
      imageSrc: commons("Honeymoon Bay Sunset 2.jpg"),
      imageAlt: "Закат на море",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#f472b6", color: "#f472b6" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#f59e0b", color: "#f59e0b" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "color-wheel": [
    {
      id: "wheel-complement",
      prompt: "Найди дополнительный цвет к #3b82f6.",
      helper: "Дополнительный цвет находится напротив на круге.",
      explanation: "Для синего #3b82f6 комплемент — насыщенный оранжевый.",
      imageSrc: commons("Color Wheel.png"),
      imageAlt: "Цветовой круг",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#f97316", color: "#f97316" },
        { label: "#10b981", color: "#10b981" },
        { label: "#a855f7", color: "#a855f7" },
        { label: "#ef4444", color: "#ef4444" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "wheel-analog",
      prompt: "Выбери аналоговый оттенок к #22c55e.",
      helper: "Аналоговые — рядом на цветовом круге.",
      explanation: "Аналоговый зелёный близок по тону и насыщенности.",
      imageSrc: commons("Color Wheel.png"),
      imageAlt: "Цветовой круг",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#16a34a", color: "#16a34a" },
        { label: "#f97316", color: "#f97316" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#ef4444", color: "#ef4444" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "wheel-complement-2",
      prompt: "Найди комплементарный цвет к #ef4444.",
      helper: "Красный дополняется зелёным.",
      explanation: "Комплементарный к красному — зелёный оттенок.",
      imageSrc: commons("Color Wheel.png"),
      imageAlt: "Цветовой круг",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#22c55e", color: "#22c55e" },
        { label: "#3b82f6", color: "#3b82f6" },
        { label: "#a855f7", color: "#a855f7" },
        { label: "#f59e0b", color: "#f59e0b" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
  "film-type": [
    {
      id: "film-bw",
      prompt: "Какой тип плёнки ближе всего по характеру изображения?",
      helper: "Обрати внимание на тональность и зерно.",
      explanation: "Контрастное чёрно-белое изображение похоже на классическую B/W плёнку.",
      imageSrc: commons("Migrant_Mother_(LOC_fsa.8b29516).jpg"),
      imageAlt: "Портрет в чёрно-белой гамме",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "Ilford HP5" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Velvia 50" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-vivid",
      prompt: "Какой тип плёнки ближе всего к этой цветопередаче?",
      helper: "Очень насыщенные цвета.",
      explanation: "Velvia известна сверхнасыщенными цветами и контрастом.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Яркий пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Velvia 50" },
        { label: "Kodak Portra 400" },
        { label: "Ilford HP5" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-night-cinestill",
      prompt: "Какая плёнка лучше всего передаст ночные неоновые огни?",
      helper: "Ищи киношный оттенок ночного света.",
      explanation: "Cinestill 800T рассчитана на ночные сцены с тёплыми огнями.",
      imageSrc: commons("Las Vegas (Nevada, USA), The Strip -- 2012 -- 6232.jpg"),
      imageAlt: "Ночной город с неоном",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Cinestill 800T" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Velvia 50" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-warm-gold",
      prompt: "Какая плёнка даёт такую тёплую, золотистую подачу?",
      helper: "Тёплые и солнечные тона.",
      explanation: "Kodak Gold известна мягкими золотистыми оттенками.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Тёплый закат",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Gold 200" },
        { label: "Fujifilm Pro 400H" },
        { label: "Kodak Ektar 100" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "film-pastel-400h",
      prompt: "Какая плёнка ближе к этой пастельной цветопередаче?",
      helper: "Мягкие цвета и низкий контраст.",
      explanation: "Fujifilm Pro 400H даёт пастельные, мягкие оттенки.",
      imageSrc: commons("Lake Sylvester during the sunrise, Kahurangi, New Zealand.jpg"),
      imageAlt: "Озеро на рассвете",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Pro 400H" },
        { label: "Fujifilm Velvia 50" },
        { label: "Kodak Ektar 100" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-ektar-mountain",
      prompt: "Какая плёнка ближе всего к такой насыщенной палитре?",
      helper: "Высокая насыщенность и контраст.",
      explanation: "Kodak Ektar 100 известна яркими и чистыми цветами.",
      imageSrc: commons("Zagedan Lakes, Mountain cirque, Caucasus Mountains.jpg"),
      imageAlt: "Горные озёра",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Ektar 100" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Pro 400H" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "film-trix-bridge",
      prompt: "Какой тип плёнки ближе всего по характеру контраста?",
      helper: "Классическая чёрно-белая подача.",
      explanation: "Kodak Tri-X даёт контрастную чёрно-белую картинку.",
      imageSrc: commons("Manhattan Bridge Construction 1909.jpg"),
      imageAlt: "Мост, чёрно-белое фото",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-contain",
      options: [
        { label: "Kodak Tri-X 400" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Velvia 50" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-portra-market",
      prompt: "Какая плёнка ближе к натуральным тонам кожи и среды?",
      helper: "Мягкая и естественная цветопередача.",
      explanation: "Kodak Portra 400 известна натуральными оттенками кожи.",
      imageSrc: commons("Moore Street market, Dublin.jpg"),
      imageAlt: "Рынок на улице",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Portra 400" },
        { label: "Kodak Ektar 100" },
        { label: "Fujifilm Velvia 50" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-velvia-snow",
      prompt: "Какая плёнка подойдёт для ярких, контрастных пейзажей?",
      helper: "Сильный контраст и холодные тона.",
      explanation: "Velvia подчёркивает контраст и насыщенность.",
      imageSrc: commons("Mountains in snow, Mountain lake, Chola Valley, Nepal, Himalayas.jpg"),
      imageAlt: "Горы и снег",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Velvia 50" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Pro 400H" },
        { label: "Kodak Gold 200" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-superia-forest",
      prompt: "Какая плёнка ближе всего к зелёным тонам на фото?",
      helper: "Зелёные выглядят холодными и сочными.",
      explanation: "Fujifilm Superia даёт прохладные зелёные оттенки.",
      imageSrc: commons("Spruce forest at Holma.jpg"),
      imageAlt: "Еловый лес",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Superia 200" },
        { label: "Kodak Portra 400" },
        { label: "Kodak Gold 200" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-ektar-city",
      prompt: "Какая плёнка подходит для яркого городского пейзажа?",
      helper: "Насыщенные тона и чёткие детали.",
      explanation: "Kodak Ektar 100 подчёркивает насыщенность и детализацию.",
      imageSrc: commons("Lower Manhattan from Jersey City July 2014 002.jpg"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Ektar 100" },
        { label: "Fujifilm Pro 400H" },
        { label: "Kodak Portra 400" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "film-portra-coast",
      prompt: "Какая плёнка ближе всего к мягкой тёплой подаче?",
      helper: "Естественные тона кожи и моря.",
      explanation: "Portra 400 сохраняет тёплую, натуральную палитру.",
      imageSrc: commons("Acapulco fishermen.jpg"),
      imageAlt: "Рыбаки у моря",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Portra 400" },
        { label: "Kodak Gold 200" },
        { label: "Fujifilm Velvia 50" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "composition-technique": [
    {
      id: "composition-thirds",
      prompt: "Какой приём композиции использован?",
      helper: "Горизонт и акценты смещены от центра.",
      explanation: "Композиция построена по правилу третей.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Горный пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Правило третей" },
        { label: "Центральная симметрия" },
        { label: "Золотая спираль" },
        { label: "Плоская композиция" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "composition-center",
      prompt: "Определи композиционный приём.",
      helper: "Главный объект расположен по центру.",
      explanation: "Это центральная композиция — объект в фокусе по оси.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок по центру кадра",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "Центральная композиция" },
        { label: "Диагонали" },
        { label: "Золотое сечение" },
        { label: "Ритмический повтор" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-diagonal",
      prompt: "Какой приём композиции здесь использован?",
      helper: "Главные линии идут по диагонали.",
      explanation: "Диагональная композиция создаёт динамику.",
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: "Земля",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "Диагональная композиция" },
        { label: "Строгая симметрия" },
        { label: "Центральная композиция" },
        { label: "Ритмический повтор" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-leading-lines",
      prompt: "Определи композиционный приём.",
      helper: "Линии уводят взгляд вдаль.",
      explanation: "Ведущие линии направляют внимание к главному объекту.",
      imageSrc: commons("Vasco da Gama Bridge B&W (crop2).jpg"),
      imageAlt: "Мост с перспективой",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Ведущие линии" },
        { label: "Центральная композиция" },
        { label: "Негативное пространство" },
        { label: "Ритмический повтор" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-symmetry",
      prompt: "Какой приём композиции доминирует?",
      helper: "Левая и правая части сбалансированы.",
      explanation: "Композиция построена на симметрии.",
      imageSrc: commons("Bridge and deck of Gullbritt.jpg"),
      imageAlt: "Симметричный мост",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Симметрия" },
        { label: "Диагонали" },
        { label: "Золотая спираль" },
        { label: "Случайное расположение" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-negative-space",
      prompt: "Какой приём композиции используется?",
      helper: "В кадре много воздуха и пустоты.",
      explanation: "Негативное пространство подчёркивает главный объект.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Закат с большим небом",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Негативное пространство" },
        { label: "Ритмический повтор" },
        { label: "Диагональная композиция" },
        { label: "Симметрия" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "composition-repetition",
      prompt: "Определи композиционный приём.",
      helper: "Много повторяющихся вертикалей.",
      explanation: "Повтор элементов создаёт ритм.",
      imageSrc: commons(
        "Beech Forest (AU), Great Otway National Park, Beauchamp Falls -- 2019 -- 1271.jpg"
      ),
      imageAlt: "Лес с повторяющимися стволами",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Ритмический повтор" },
        { label: "Центральная композиция" },
        { label: "Негативное пространство" },
        { label: "Правило третей" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-framing",
      prompt: "Какой приём композиции заметен в кадре?",
      helper: "Кадр будто обрамлён природными элементами.",
      explanation: "Обрамление направляет взгляд внутрь сцены.",
      imageSrc: commons(
        "Gyedong-gil street with climbing plants at golden hour in Seoul South Korea.jpg"
      ),
      imageAlt: "Улица с зелёным обрамлением",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Обрамление" },
        { label: "Симметрия" },
        { label: "Диагонали" },
        { label: "Плоская композиция" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-depth-layers",
      prompt: "Какой приём композиции здесь использован?",
      helper: "Есть передний, средний и дальний планы.",
      explanation: "Слои создают ощущение глубины.",
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: "Озеро с планами",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Слои и глубина" },
        { label: "Негативное пространство" },
        { label: "Плоская композиция" },
        { label: "Симметрия" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-s-curve",
      prompt: "Какой приём композиции здесь заметен?",
      helper: "Линия в кадре плавно изгибается.",
      explanation: "S-образная линия ведёт взгляд и создаёт динамику.",
      imageSrc: commons("Rogue River Oregon USA.jpg"),
      imageAlt: "Извилистая река",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "S-образная линия" },
        { label: "Центральная композиция" },
        { label: "Ритмический повтор" },
        { label: "Золотое сечение" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "composition-pattern",
      prompt: "Какой приём композиции доминирует?",
      helper: "Повторяющиеся элементы строят узор.",
      explanation: "Композиция опирается на паттерн и ритм.",
      imageSrc: commons("Wet market in Singapore 2.jpg"),
      imageAlt: "Рынок с повторяющимися формами",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Паттерн и повтор" },
        { label: "Негативное пространство" },
        { label: "Диагональная композиция" },
        { label: "Симметрия" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-silhouette",
      prompt: "Какой приём композиции здесь использован?",
      helper: "Контраст между объектом и ярким фоном.",
      explanation: "Силуэт подчёркивает форму и контраст.",
      imageSrc: commons("Honeymoon Bay Sunset 2.jpg"),
      imageAlt: "Закат с силуэтами",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Силуэт" },
        { label: "Обрамление" },
        { label: "Ритмический повтор" },
        { label: "Центральная композиция" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "composition-perspective",
      prompt: "Какой приём композиции здесь заметен?",
      helper: "Глубина создаётся линиями перспективы.",
      explanation: "Линейная перспектива усиливает ощущение пространства.",
      imageSrc: commons("NYC wideangle south from Top of the Rock.jpg"),
      imageAlt: "Город с перспективой",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Линейная перспектива" },
        { label: "Негативное пространство" },
        { label: "Симметрия" },
        { label: "Плоская композиция" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "focal-length": [
    {
      id: "focal-portrait",
      prompt: "Какое фокусное расстояние вероятнее всего?",
      helper: "Смотри на перспективу и искажения.",
      explanation: "Портрет без сильных искажений — около 85 мм.",
      imageSrc: commons("Migrant_Mother_(LOC_fsa.8b29516).jpg"),
      imageAlt: "Портрет",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-wide",
      prompt: "Определи фокусное расстояние по перспективе.",
      helper: "Широкий угол даёт ощущение пространства.",
      explanation: "Пейзаж с выраженной перспективой чаще снимают на 24 мм.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "focal-normal",
      prompt: "Какое фокусное расстояние наиболее вероятно?",
      helper: "Перспектива выглядит естественной.",
      explanation: "Нормальный объектив для такой перспективы — около 50 мм.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-nyc-wide",
      prompt: "Какое фокусное расстояние вероятнее всего для такого кадра?",
      helper: "Сильная перспектива и широкий охват.",
      explanation: "Широкоугольный кадр чаще всего снимают на 24 мм.",
      imageSrc: commons("NYC wideangle south from Top of the Rock.jpg"),
      imageAlt: "Широкий городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "16 мм" },
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "medium",
    },
    {
      id: "focal-manhattan-tele",
      prompt: "Какое фокусное расстояние ближе для такого сжатого плана?",
      helper: "Перспектива выглядит чуть сжатой.",
      explanation: "Умеренно-телеобъектив около 85 мм даёт такое сжатие.",
      imageSrc: commons("Lower Manhattan from Jersey City July 2014 002.jpg"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-himalayas-tele",
      prompt: "Какое фокусное расстояние ближе для такого горного плана?",
      helper: "Горы выглядят приближенными и сжатыми.",
      explanation: "Телеобъектив около 135 мм сжимает перспективу.",
      imageSrc: commons("Himalayas, Ama Dablam, Nepal.jpg"),
      imageAlt: "Горы",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 3,
      difficulty: "hard",
    },
    {
      id: "focal-everest-tele",
      prompt: "Какое фокусное расстояние вероятнее всего здесь?",
      helper: "Очень сильное сжатие дальних планов.",
      explanation: "Длинный фокус порядка 200 мм сжимает перспективу.",
      imageSrc: commons("Everest, Himalayas.jpg"),
      imageAlt: "Горный хребет",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
        { label: "200 мм" },
      ],
      correctIndex: 3,
      difficulty: "hard",
    },
    {
      id: "focal-sunset-normal",
      prompt: "Какое фокусное расстояние ближе для такого кадра?",
      helper: "Перспектива выглядит естественной, без сильных искажений.",
      explanation: "Умеренно широкий объектив около 35 мм даёт такой эффект.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Закат",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "easy",
    },
    {
      id: "focal-waterfall-wide",
      prompt: "Какое фокусное расстояние ближе всего?",
      helper: "Кадр широкого пейзажа с большим охватом.",
      explanation: "Широкий угол около 24 мм подходит для таких сцен.",
      imageSrc: commons("Chamarel Falls Mauritius 2.JPG"),
      imageAlt: "Водопад",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "16 мм" },
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "medium",
    },
    {
      id: "focal-market-normal",
      prompt: "Какое фокусное расстояние вероятнее всего?",
      helper: "Перспектива выглядит близкой к естественной.",
      explanation: "Около 50 мм даёт привычную перспективу.",
      imageSrc: commons("Moore Street market, Dublin.jpg"),
      imageAlt: "Уличный рынок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 2,
      difficulty: "easy",
    },
    {
      id: "focal-fishermen-portrait",
      prompt: "Какое фокусное расстояние ближе для этого плана?",
      helper: "Объект выделен, фон слегка сжат.",
      explanation: "Портретный диапазон около 85 мм подходит лучше всего.",
      imageSrc: commons("Acapulco fishermen.jpg"),
      imageAlt: "Рыбаки",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-bazaar-mid",
      prompt: "Какое фокусное расстояние вероятнее всего?",
      helper: "Кадр не слишком широкий и не слишком тесный.",
      explanation: "Умеренно широкий объектив около 35 мм выглядит правдоподобно.",
      imageSrc: commons("Grand-Bazaar Shop.jpg"),
      imageAlt: "Внутри магазина",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "medium",
    },
    {
      id: "focal-lake-normal",
      prompt: "Какое фокусное расстояние ближе всего?",
      helper: "Перспектива спокойная и без искажений.",
      explanation: "Около 50 мм даёт естественный масштаб.",
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: "Озеро",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 2,
      difficulty: "easy",
    },
  ],
  "wcag-issue": [
    {
      id: "wcag-contrast",
      prompt: "Какая проблема доступности видна на макете?",
      helper: "Сравни контраст текста и фона.",
      explanation: "Текст имеет слишком низкий контраст и не проходит WCAG.",
      imageSrc: "/stock/ui-accessibility.svg",
      imageAlt: "Макет с низким контрастом текста",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "Недостаточный контраст" },
        { label: "Слишком мелкий кегль" },
        { label: "Слабая иерархия" },
        { label: "Нет отступов" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "wcag-small-text",
      prompt: "Какая проблема доступности здесь?",
      helper: "Оцени размер текста.",
      explanation: "Текст слишком мелкий — нарушена минимальная читаемость.",
      imageSrc: "/stock/ui-accessibility-smalltext.svg",
      imageAlt: "Мелкий текст",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "Слишком маленький текст" },
        { label: "Низкий контраст" },
        { label: "Нет фокуса" },
        { label: "Слишком яркий фон" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
  "button-color": [
    {
      id: "button-contrast",
      prompt: "Подбери цвет кнопки с достаточным контрастом.",
      helper: "Кнопка должна выделяться на светлом фоне.",
      explanation: "Насыщенный синий даёт лучший контраст и читаемость.",
      imageSrc: "/stock/ui-button-color.svg",
      imageAlt: "Макет с выбором цвета кнопки",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#1a73e8", color: "#1a73e8" },
        { label: "#9aa0a6", color: "#9aa0a6" },
        { label: "#fbbc04", color: "#fbbc04" },
        { label: "#e0e0e0", color: "#e0e0e0" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "button-dark",
      prompt: "Подбери контрастный цвет кнопки на тёмном фоне.",
      helper: "Нужен яркий, но читаемый оттенок.",
      explanation: "Светлый голубой лучше всего выделяется на тёмном фоне.",
      imageSrc: "/stock/ui-button-color-dark.svg",
      imageAlt: "Тёмный экран подписки",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#60a5fa", color: "#60a5fa" },
        { label: "#374151", color: "#374151" },
        { label: "#111827", color: "#111827" },
        { label: "#9ca3af", color: "#9ca3af" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "font-size-choice": [
    {
      id: "font-size-ui",
      prompt: "Какой размер основного текста здесь уместен?",
      helper: "Учти читаемость интерфейса.",
      explanation: "Для интерфейсов обычно выбирают 16px как базовый размер.",
      imageSrc: "/stock/ui-font-size.svg",
      imageAlt: "Макет с инструкцией",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "12 px", size: 12 },
        { label: "14 px", size: 14 },
        { label: "16 px", size: 16 },
        { label: "18 px", size: 18 },
      ],
      correctIndex: 2,
      difficulty: "easy",
    },
    {
      id: "font-size-compact",
      prompt: "Какой размер текста поможет улучшить читаемость?",
      helper: "Сейчас текст выглядит слишком мелким.",
      explanation: "Размер 16px даёт комфортную читаемость в интерфейсе.",
      imageSrc: "/stock/ui-font-size-compact.svg",
      imageAlt: "Плотный интерфейс",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "14 px", size: 14 },
        { label: "16 px", size: 16 },
        { label: "18 px", size: 18 },
        { label: "12 px", size: 12 },
      ],
      correctIndex: 1,
      difficulty: "easy",
    },
  ],
  "layout-error": [
    {
      id: "layout-error-grid",
      prompt: "Что не так в вёрстке?",
      helper: "Обрати внимание на сетку карточек.",
      explanation: "Правая карточка смещена по вертикали — нарушена сетка.",
      imageSrc: "/stock/ui-layout-error.svg",
      imageAlt: "Макет с ошибкой в сетке",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "Нарушено выравнивание по сетке" },
        { label: "Недостаточный контраст" },
        { label: "Слишком маленькие кликабельные зоны" },
        { label: "Слишком много цвета" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "layout-error-spacing",
      prompt: "Найди проблему в макете.",
      helper: "Сравни вертикальные отступы.",
      explanation: "Нарушен вертикальный ритм между элементами списка.",
      imageSrc: "/stock/ui-layout-error-spacing.svg",
      imageAlt: "Список с лишним отступом",
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "Нарушен вертикальный ритм" },
        { label: "Плохой контраст" },
        { label: "Слабая иерархия" },
        { label: "Нет состояния hover" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
  "palette-from-photo": [
    {
      id: "palette-flower",
      prompt: "Выбери палитру, которая ближе всего к фото.",
      helper: "Смотри на доминирующие цвета.",
      explanation: "Палитра включает красный цвет лепестков и приглушённый зелёный фон.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "Тёплая", palette: ["#e24b4b", "#f2c94c", "#5c6b4f"] },
        { label: "Холодная", palette: ["#2d9cdb", "#6c5ce7", "#00b894"] },
        { label: "Нейтральная", palette: ["#7f8c8d", "#bdc3c7", "#ecf0f1"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-earth",
      prompt: "Какая палитра ближе всего к этому снимку?",
      helper: "Учти синие океаны и белые облака.",
      explanation: "Палитра включает насыщенный синий и светлые нейтрали.",
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: "Земля из космоса",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "Небо", palette: ["#1f5fbf", "#4f7fbf", "#d9e2ec"] },
        { label: "Лес", palette: ["#166534", "#4d7c0f", "#854d0e"] },
        { label: "Тепло", palette: ["#f59e0b", "#f97316", "#ef4444"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-sunset-amber",
      prompt: "Выбери палитру, которая ближе всего к закату.",
      helper: "Тёплые оттенки неба и приглушённые тени.",
      explanation: "Палитра включает янтарные и оранжевые оттенки с тёмной тенью.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Закат",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Тёплый закат", palette: ["#f59e0b", "#fb923c", "#334155"] },
        { label: "Холодный", palette: ["#0ea5e9", "#1d4ed8", "#0f172a"] },
        { label: "Зелёный", palette: ["#22c55e", "#15803d", "#065f46"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-ocean-coast",
      prompt: "Какая палитра ближе всего к морскому берегу?",
      helper: "Ищи голубые и бирюзовые оттенки.",
      explanation: "Палитра сочетает голубой, бирюзу и светлый песок.",
      imageSrc: commons("Ocean beach at low tide against the sun.jpg"),
      imageAlt: "Берег океана",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Берег", palette: ["#0ea5e9", "#14b8a6", "#f8fafc"] },
        { label: "Пустыня", palette: ["#d97706", "#f59e0b", "#78350f"] },
        { label: "Город", palette: ["#475569", "#94a3b8", "#e2e8f0"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-forest-deep",
      prompt: "Выбери палитру, которая ближе всего к лесу.",
      helper: "Обрати внимание на тёмные зелёные и коричневые.",
      explanation: "Палитра сочетает глубокий зелёный и землистые тона.",
      imageSrc: commons(
        "Beech Forest (AU), Great Otway National Park, Beauchamp Falls -- 2019 -- 1271.jpg"
      ),
      imageAlt: "Лес",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Лес", palette: ["#2f855a", "#4b5563", "#7c6f57"] },
        { label: "Закат", palette: ["#f59e0b", "#ef4444", "#1f2937"] },
        { label: "Океан", palette: ["#0ea5e9", "#0369a1", "#f8fafc"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-desert-oasis",
      prompt: "Какая палитра ближе всего к пустынному пейзажу?",
      helper: "Смотри на тёплые песочные оттенки.",
      explanation: "Палитра строится вокруг охры и тёмных теней.",
      imageSrc: commons("Acacia in Ein Khadra Desert Oasis 00 (87).jpg"),
      imageAlt: "Пустыня",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Песок", palette: ["#d97706", "#f59e0b", "#475569"] },
        { label: "Лес", palette: ["#22c55e", "#166534", "#14532d"] },
        { label: "Ночь", palette: ["#0f172a", "#1e293b", "#334155"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-aurora",
      prompt: "Какая палитра ближе всего к полярному сиянию?",
      helper: "Зелёное сияние на тёмном небе.",
      explanation: "Палитра сочетает зелёный неон и глубокий синий.",
      imageSrc: commons("Virmalised 15.09.2017 - Aurora Borealis 15.09.2017 copy.jpg"),
      imageAlt: "Полярное сияние",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Сияние", palette: ["#22c55e", "#0ea5e9", "#0f172a"] },
        { label: "Осень", palette: ["#f97316", "#b45309", "#7c2d12"] },
        { label: "Пастель", palette: ["#f9a8d4", "#93c5fd", "#e2e8f0"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-lake-turquoise",
      prompt: "Выбери палитру, которая ближе всего к горному озеру.",
      helper: "Вода выглядит холодной и бирюзовой.",
      explanation: "Палитра состоит из бирюзы, холодного синего и серых скал.",
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: "Горное озеро",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Озеро", palette: ["#14b8a6", "#0ea5e9", "#94a3b8"] },
        { label: "Пустыня", palette: ["#f59e0b", "#d97706", "#78350f"] },
        { label: "Лес", palette: ["#22c55e", "#15803d", "#065f46"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-flower-pink",
      prompt: "Какая палитра ближе всего к цветку?",
      helper: "Смотри на розовые и светлые оттенки.",
      explanation: "Палитра включает розовый и светлые нейтрали.",
      imageSrc: commons(
        "Stargazer Lillies Lillium orientale 'Stargazer' Flower 2000px.jpg"
      ),
      imageAlt: "Розовые цветы",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "Цветок", palette: ["#ec4899", "#f9a8d4", "#f8fafc"] },
        { label: "Ночь", palette: ["#0f172a", "#1e293b", "#334155"] },
        { label: "Лес", palette: ["#22c55e", "#166534", "#14532d"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-market-warm",
      prompt: "Выбери палитру, которая ближе всего к рынку.",
      helper: "Ищи тёплые, насыщенные цвета.",
      explanation: "Палитра строится на тёплых охристых оттенках.",
      imageSrc: commons("Grand-Bazaar Shop.jpg"),
      imageAlt: "Рынок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Тёплая", palette: ["#b45309", "#f59e0b", "#7c2d12"] },
        { label: "Холодная", palette: ["#0ea5e9", "#1d4ed8", "#0f172a"] },
        { label: "Пастель", palette: ["#f9a8d4", "#93c5fd", "#e2e8f0"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-night-city",
      prompt: "Какая палитра ближе всего к ночному городу?",
      helper: "Неоновые акценты на тёмном фоне.",
      explanation: "Палитра сочетает холодный синий, тёплый неон и фиолетовый.",
      imageSrc: commons("Las Vegas (Nevada, USA), The Strip -- 2012 -- 6232.jpg"),
      imageAlt: "Ночной город",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Неон", palette: ["#0ea5e9", "#f97316", "#a855f7"] },
        { label: "Монохром", palette: ["#334155", "#64748b", "#e2e8f0"] },
        { label: "Лес", palette: ["#22c55e", "#15803d", "#065f46"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-snow-blue",
      prompt: "Какая палитра ближе всего к зимнему пейзажу?",
      helper: "Снег и холодные тени.",
      explanation: "Палитра включает холодный белый, голубой и серый.",
      imageSrc: commons("Snow Scene at Shipka Pass 1.JPG"),
      imageAlt: "Зимний пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Зима", palette: ["#e5e7eb", "#93c5fd", "#64748b"] },
        { label: "Осень", palette: ["#f59e0b", "#d97706", "#78350f"] },
        { label: "Тропики", palette: ["#22c55e", "#14b8a6", "#0ea5e9"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
};
