import { GameId } from "@/types";
import { Difficulty } from "@/utils/difficulty";
import { LocalizedText } from "@/utils/i18n";

export interface ImageQuizSource {
  label: string | LocalizedText;
  url?: string;
}

export interface ImageQuizOption {
  label: string | LocalizedText;
  color?: string;
  palette?: string[];
  size?: number;
}

export interface ImageQuizQuestion {
  id: string;
  prompt: string | LocalizedText;
  helper?: string | LocalizedText;
  explanation: string | LocalizedText;
  imageSrc: string;
  imageAlt: string | LocalizedText;
  imageSource?: ImageQuizSource;
  imageContainerClass?: string;
  imageFrameClass?: string;
  imageClass?: string;
  options: ImageQuizOption[];
  correctIndex: number;
  difficulty?: Difficulty;
}

export const IMAGE_QUIZ_IDS = [
  "artist-guess",
  "style-guess",
  "image-size",
  "image-format",
  "color-eye",
  "color-wheel",
  "film-type",
  "composition-technique",
  "focal-length",
  "wcag-issue",
  "button-color",
  "font-size-choice",
  "layout-error",
  "palette-from-photo",
] as const satisfies GameId[];

export type ImageQuizGameId = (typeof IMAGE_QUIZ_IDS)[number];

const commons = (file: string, width = 1200) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${width}`;

const sources = {
  commons: { label: { ru: "Wikimedia Commons", en: "Wikimedia Commons" }, url: "https://commons.wikimedia.org" },
  internal: { label: { ru: "Внутренний макет", en: "Internal mockup" } },
};

const text = (ru: string, en: string): LocalizedText => ({ ru, en });

export const IMAGE_QUIZ_DATA: Record<ImageQuizGameId, ImageQuizQuestion[]> = {
  "artist-guess": [
    {
      id: "artist-mona-lisa",
      prompt: text("Кто автор этой работы?", "Who is the author of this work?"),
      helper: text("Обрати внимание на эпоху и манеру письма.", "Pay attention to the era and manner of painting."),
      explanation: text(
        "«Мона Лиза» — работа Леонардо да Винчи эпохи Возрождения.",
        "The Mona Lisa is a Renaissance work by Leonardo da Vinci.",
      ),
      imageSrc: commons("Mona_Lisa.jpg"),
      imageAlt: text("Мона Лиза", "Mona Lisa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Леонардо да Винчи", "Leonardo da Vinci") },
        { label: text("Рафаэль", "Raphael") },
        { label: text("Сандро Боттичелли", "Sandro Botticelli") },
        { label: text("Рембрандт", "Rembrandt") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "artist-venus",
      prompt: text("Кто написал эту картину?", "Who painted this work?"),
      helper: text(
        "Обрати внимание на плавные линии и мифологический сюжет.",
        "Look for flowing lines and a mythological subject.",
      ),
      explanation: text("«Рождение Венеры» — Сандро Боттичелли.", "The Birth of Venus is by Sandro Botticelli."),
      imageSrc: commons("Birth_of_Venus_Botticelli.jpg"),
      imageAlt: text("Рождение Венеры", "The Birth of Venus"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Сандро Боттичелли", "Sandro Botticelli") },
        { label: text("Тициан", "Titian") },
        { label: text("Леонардо да Винчи", "Leonardo da Vinci") },
        { label: text("Рафаэль", "Raphael") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-monet",
      prompt: text("Определи художника по работе.", "Identify the artist from the work."),
      helper: text("Эта картина дала имя целому направлению.", "This painting gave a name to an entire movement."),
      explanation: text(
        "«Impression, soleil levant» — Клод Моне, основатель импрессионизма.",
        "Impression, Sunrise is by Claude Monet, founder of Impressionism.",
      ),
      imageSrc: commons("Claude_Monet,_Impression,_soleil_levant.jpg"),
      imageAlt: text("Impression, soleil levant", "Impression, Sunrise"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Клод Моне", "Claude Monet") },
        { label: text("Эдгар Дега", "Edgar Degas") },
        { label: text("Пьер-Огюст Ренуар", "Pierre-Auguste Renoir") },
        { label: text("Камиль Писсарро", "Camille Pissarro") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-wave",
      prompt: text("Кто автор этой гравюры?", "Who is the author of this print?"),
      helper: text("Гравюра с выразительными линиями и морской темой.", "A print with strong lines and a sea theme."),
      explanation: text(
        "«Большая волна в Канагаве» — Кацусика Хокусай.",
        "The Great Wave off Kanagawa is by Katsushika Hokusai.",
      ),
      imageSrc: commons("Great_Wave_off_Kanagawa.jpg"),
      imageAlt: text("Большая волна в Канагаве", "The Great Wave off Kanagawa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Кацусика Хокусай", "Katsushika Hokusai") },
        { label: text("Утагава Хиросигэ", "Utagawa Hiroshige") },
        { label: text("Китагава Утамаро", "Kitagawa Utamaro") },
        { label: text("Сэссю Тойо", "Sesshu Toyo") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-vermeer",
      prompt: text("Кто автор этого портрета?", "Who painted this portrait?"),
      helper: text("Нидерландская живопись XVII века.", "Dutch painting of the 17th century."),
      explanation: text(
        "«Девушка с жемчужной серёжкой» — Ян Вермеер.",
        "Girl with a Pearl Earring is by Johannes Vermeer.",
      ),
      imageSrc: commons("Girl_with_a_Pearl_Earring.jpg"),
      imageAlt: text("Девушка с жемчужной серёжкой", "Girl with a Pearl Earring"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Ян Вермеер", "Johannes Vermeer") },
        { label: text("Питер Пауль Рубенс", "Peter Paul Rubens") },
        { label: text("Рембрандт", "Rembrandt") },
        { label: text("Ян ван Эйк", "Jan van Eyck") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "artist-bosch",
      prompt: text("Определи автора этой работы.", "Identify the author of this work."),
      helper: text(
        "Многофигурная аллегорическая сцена с множеством деталей.",
        "A multi-figure allegorical scene full of details.",
      ),
      explanation: text("«Сад земных наслаждений» — Иероним Босх.", "The Garden of Earthly Delights is by Hieronymus Bosch."),
      imageSrc: commons("Garden_of_Earthly_Delights.jpg"),
      imageAlt: text("Сад земных наслаждений", "The Garden of Earthly Delights"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Иероним Босх", "Hieronymus Bosch") },
        { label: text("Питер Брейгель", "Pieter Bruegel") },
        { label: text("Альбрехт Дюрер", "Albrecht Durer") },
        { label: text("Фра Беато Анджелико", "Fra Angelico") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
  ],
  "style-guess": [
    {
      id: "style-renaissance",
      prompt: text("Определи стиль по изображению.", "Identify the style from the image."),
      helper: text("Внимание к анатомии и светотени.", "Focus on anatomy and chiaroscuro."),
      explanation: text(
        "«Мона Лиза» относится к эпохе Высокого Возрождения.",
        "The Mona Lisa belongs to the High Renaissance.",
      ),
      imageSrc: commons("Mona_Lisa.jpg"),
      imageAlt: text("Мона Лиза", "Mona Lisa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Ренессанс", "Renaissance") },
        { label: text("Барокко", "Baroque") },
        { label: text("Кубизм", "Cubism") },
        { label: text("Сюрреализм", "Surrealism") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "style-impressionism",
      prompt: text("Какой это стиль?", "What style is this?"),
      helper: text("Размытые мазки, свет и воздух.", "Blurred strokes, light, and air."),
      explanation: text("Картина Моне стала символом импрессионизма.", "Monet's painting became a symbol of Impressionism."),
      imageSrc: commons("Claude_Monet,_Impression,_soleil_levant.jpg"),
      imageAlt: text("Impression, soleil levant", "Impression, Sunrise"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Импрессионизм", "Impressionism") },
        { label: text("Экспрессионизм", "Expressionism") },
        { label: text("Неоклассицизм", "Neoclassicism") },
        { label: text("Поп-арт", "Pop Art") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "style-ukiyo",
      prompt: text("Определи стиль гравюры.", "Identify the style of the print."),
      helper: text("Плоскостные формы и декоративный рисунок.", "Flat shapes and decorative linework."),
      explanation: text("Укиё-э — традиционная японская графика.", "Ukiyo-e is traditional Japanese printmaking."),
      imageSrc: commons("Great_Wave_off_Kanagawa.jpg"),
      imageAlt: text("Большая волна в Канагаве", "The Great Wave off Kanagawa"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Укиё-э", "Ukiyo-e") },
        { label: text("Романтизм", "Romanticism") },
        { label: text("Реализм", "Realism") },
        { label: text("Барокко", "Baroque") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "style-early-renaissance",
      prompt: text("Выбери стиль картины.", "Choose the style of the painting."),
      helper: text("Мифологический сюжет и плавные линии.", "Mythological subject and flowing lines."),
      explanation: text(
        "«Рождение Венеры» — ранний итальянский Ренессанс.",
        "The Birth of Venus is Early Italian Renaissance.",
      ),
      imageSrc: commons("Birth_of_Venus_Botticelli.jpg"),
      imageAlt: text("Рождение Венеры", "The Birth of Venus"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Ранний Ренессанс", "Early Renaissance") },
        { label: text("Готика", "Gothic") },
        { label: text("Барокко", "Baroque") },
        { label: text("Рококо", "Rococo") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "style-baroque",
      prompt: text("Определи стиль по живописи.", "Identify the style from the painting."),
      helper: text("Драматическое освещение и пластика форм.", "Dramatic lighting and sculptural forms."),
      explanation: text(
        "Барокко характерно сильным светотеневым контрастом.",
        "Baroque is known for strong light–shadow contrast.",
      ),
      imageSrc: commons("Girl_with_a_Pearl_Earring.jpg"),
      imageAlt: text("Портрет", "Portrait"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[3/4] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Барокко", "Baroque") },
        { label: text("Кубизм", "Cubism") },
        { label: text("Футуризм", "Futurism") },
        { label: text("Сюрреализм", "Surrealism") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "style-northern-renaissance",
      prompt: text("Выбери стиль этой работы.", "Choose the style of this work."),
      helper: text("Сложная символика и аллегории.", "Complex symbolism and allegory."),
      explanation: text(
        "Северное Возрождение — характерная детализация и символизм.",
        "Northern Renaissance is known for detailed rendering and symbolism.",
      ),
      imageSrc: commons("Garden_of_Earthly_Delights.jpg"),
      imageAlt: text("Сад земных наслаждений", "The Garden of Earthly Delights"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Северное Возрождение", "Northern Renaissance") },
        { label: text("Романтизм", "Romanticism") },
        { label: text("Импрессионизм", "Impressionism") },
        { label: text("Поп-арт", "Pop Art") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
  ],
  "image-size": [
    {
      id: "size-280x180",
      prompt: text("Какой размер изображения на экране?", "What is the on-screen image size?"),
      helper: text("Оцени рамку в пикселях.", "Estimate the frame in pixels."),
      explanation: text("Кадр отображается как 280×180 px.", "The frame is displayed at 280×180 px."),
      imageSrc: commons("Example.jpg"),
      imageAlt: text("Цветок", "Flower"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[280px] h-[180px]",
      imageClass: "object-cover",
      options: [
        { label: "280×180 px" },
        { label: "320×200 px" },
        { label: "240×160 px" },
        { label: "360×240 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-360x240",
      prompt: text("Определи размер изображения.", "Identify the image size."),
      helper: text("Сравни визуальные пропорции.", "Compare the visual proportions."),
      explanation: text("Кадр задан как 360×240 px.", "The frame is set to 360×240 px."),
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: text("Горный пейзаж", "Mountain landscape"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[360px] h-[240px]",
      imageClass: "object-cover",
      options: [
        { label: "360×240 px" },
        { label: "320×200 px" },
        { label: "400×260 px" },
        { label: "280×180 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-320x200",
      prompt: text("Определи размер кадра.", "Identify the frame size."),
      helper: text("Сравни рамку с типовыми размерами.", "Compare the frame with common sizes."),
      explanation: text("Кадр задан как 320×200 px.", "The frame is set to 320×200 px."),
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: text("Планета Земля", "Planet Earth"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[320px] h-[200px]",
      imageClass: "object-cover",
      options: [
        { label: "320×200 px" },
        { label: "280×180 px" },
        { label: "360×240 px" },
        { label: "400×260 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-240x160",
      prompt: text("Какой размер изображения?", "What is the image size?"),
      helper: text("Сравни по масштабу с соседними вариантами.", "Compare the scale with nearby options."),
      explanation: text("Кадр отображается как 240×160 px.", "The frame is displayed at 240×160 px."),
      imageSrc: commons("Mountain view in Robson valley.jpg"),
      imageAlt: text("Горный пейзаж", "Mountain landscape"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[240px] h-[160px]",
      imageClass: "object-cover",
      options: [
        { label: "240×160 px" },
        { label: "280×180 px" },
        { label: "320×200 px" },
        { label: "200×140 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-300x200",
      prompt: text("Определи размер кадра.", "Identify the frame size."),
      helper: text("Смотри на пропорции и ширину.", "Look at proportions and width."),
      explanation: text("Кадр задан как 300×200 px.", "The frame is set to 300×200 px."),
      imageSrc: commons("Beach, New Brighton, New Zealand 06.jpg"),
      imageAlt: text("Пляж", "Beach"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[300px] h-[200px]",
      imageClass: "object-cover",
      options: [
        { label: "300×200 px" },
        { label: "320×200 px" },
        { label: "280×180 px" },
        { label: "360×240 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-400x260",
      prompt: text("Какой размер изображения на экране?", "What is the on-screen image size?"),
      helper: text("Оцени размеры рамки.", "Estimate the frame dimensions."),
      explanation: text("Кадр отображается как 400×260 px.", "The frame is displayed at 400×260 px."),
      imageSrc: commons("City Skyline from Above (Unsplash).jpg"),
      imageAlt: text("Городской пейзаж", "Cityscape"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[400px] h-[260px]",
      imageClass: "object-cover",
      options: [
        { label: "400×260 px" },
        { label: "360×240 px" },
        { label: "420×280 px" },
        { label: "320×200 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-360x220",
      prompt: text("Определи размер кадра.", "Identify the frame size."),
      helper: text("Сравни ширину и высоту.", "Compare width and height."),
      explanation: text("Кадр задан как 360×220 px.", "The frame is set to 360×220 px."),
      imageSrc: commons("River Cuckmere April 2018 01.jpg"),
      imageAlt: text("Река", "River"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[360px] h-[220px]",
      imageClass: "object-cover",
      options: [
        { label: "360×220 px" },
        { label: "360×240 px" },
        { label: "320×200 px" },
        { label: "400×260 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-420x280",
      prompt: text("Какой размер изображения?", "What is the image size?"),
      helper: text("Оцени рамку и площадь.", "Estimate the frame and area."),
      explanation: text("Кадр отображается как 420×280 px.", "The frame is displayed at 420×280 px."),
      imageSrc: commons("Bridge Vittorio Emanuele II at sunset.jpg"),
      imageAlt: text("Мост на закате", "Bridge at sunset"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[420px] h-[280px]",
      imageClass: "object-cover",
      options: [
        { label: "420×280 px" },
        { label: "400×260 px" },
        { label: "360×240 px" },
        { label: "320×200 px" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "size-260x180",
      prompt: text("Определи размер изображения.", "Identify the image size."),
      helper: text("Смотри на рамку и пропорции.", "Look at the frame and proportions."),
      explanation: text("Кадр задан как 260×180 px.", "The frame is set to 260×180 px."),
      imageSrc: commons("Forest road Slavne 2017 G8.jpg"),
      imageAlt: text("Лесная дорога", "Forest road"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[260px] h-[180px]",
      imageClass: "object-cover",
      options: [
        { label: "260×180 px" },
        { label: "240×160 px" },
        { label: "280×180 px" },
        { label: "300×200 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-320x180",
      prompt: text("Какой размер кадра?", "What is the frame size?"),
      helper: text("Сравни ширину и высоту.", "Compare width and height."),
      explanation: text("Кадр отображается как 320×180 px.", "The frame is displayed at 320×180 px."),
      imageSrc: commons("Night sky in the Alps - panoramio (3).jpg"),
      imageAlt: text("Ночное небо", "Night sky"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[320px] h-[180px]",
      imageClass: "object-cover",
      options: [
        { label: "320×180 px" },
        { label: "320×200 px" },
        { label: "300×200 px" },
        { label: "360×220 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-300x220",
      prompt: text("Определи размер изображения.", "Identify the image size."),
      helper: text("Оцени высоту относительно ширины.", "Estimate height relative to width."),
      explanation: text("Кадр задан как 300×220 px.", "The frame is set to 300×220 px."),
      imageSrc: commons("Lake Agnes im Banff National Park.jpg"),
      imageAlt: text("Озеро", "Lake"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[300px] h-[220px]",
      imageClass: "object-cover",
      options: [
        { label: "300×220 px" },
        { label: "320×200 px" },
        { label: "280×200 px" },
        { label: "360×240 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "size-280x200",
      prompt: text("Какой размер кадра?", "What is the frame size?"),
      helper: text("Оцени пропорции по высоте.", "Assess proportions by height."),
      explanation: text("Кадр отображается как 280×200 px.", "The frame is displayed at 280×200 px."),
      imageSrc: commons("Beach - San Agustín.jpg"),
      imageAlt: text("Пляж", "Beach"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[280px] h-[200px]",
      imageClass: "object-cover",
      options: [
        { label: "280×200 px" },
        { label: "300×200 px" },
        { label: "260×180 px" },
        { label: "320×200 px" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "size-340x220",
      prompt: text("Определи размер изображения на экране.", "Identify the on-screen image size."),
      helper: text("Сравни ширину с высотой.", "Compare width to height."),
      explanation: text("Кадр задан как 340×220 px.", "The frame is set to 340×220 px."),
      imageSrc: commons("City Skyline from balcony.jpg"),
      imageAlt: text("Городской пейзаж", "Cityscape"),
      imageSource: sources.commons,
      imageContainerClass: "flex justify-center",
      imageFrameClass: "w-[340px] h-[220px]",
      imageClass: "object-cover",
      options: [
        { label: "340×220 px" },
        { label: "360×220 px" },
        { label: "320×200 px" },
        { label: "300×200 px" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "image-format": [
    {
      id: "format-3-2",
      prompt: text("Какой формат кадра?", "What is the frame aspect ratio?"),
      helper: text("Посмотри на отношение сторон.", "Look at the aspect ratio."),
      explanation: text("Кадр задан в формате 3:2.", "The frame is in 3:2."),
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: text("Горный пейзаж", "Mountain landscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "3:2" },
        { label: "4:3" },
        { label: "16:9" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-4-3",
      prompt: text("Определи формат изображения.", "Identify the image aspect ratio."),
      helper: text("Присмотрись к рамке.", "Take a closer look at the frame."),
      explanation: text("Визуально это формат 4:3.", "Visually this is 4:3."),
      imageSrc: commons("Example.jpg"),
      imageAlt: text("Цветок", "Flower"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "4:3" },
        { label: "3:2" },
        { label: "1:1" },
        { label: "16:9" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-1-1",
      prompt: text("Какой формат кадра?", "What is the frame aspect ratio?"),
      helper: text("Кадр выглядит квадратным.", "The frame looks square."),
      explanation: text("Формат 1:1 — квадрат.", "1:1 is square."),
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: text("Земля", "Earth"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "1:1" },
        { label: "4:3" },
        { label: "3:2" },
        { label: "16:9" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-16-9",
      prompt: text("Определи формат изображения.", "Identify the image aspect ratio."),
      helper: text("Широкий кадр с низкой высотой.", "A wide frame with low height."),
      explanation: text("Это формат 16:9.", "This is 16:9."),
      imageSrc: commons("City Skyline Urban Skyscrapers (Unsplash).jpg"),
      imageAlt: text("Городской пейзаж", "Cityscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[16/9]",
      imageClass: "object-cover",
      options: [
        { label: "16:9" },
        { label: "3:2" },
        { label: "4:3" },
        { label: "2:1" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "format-2-1",
      prompt: text("Какой формат кадра?", "What is the frame aspect ratio?"),
      helper: text("Очень широкий кадр.", "Very wide frame."),
      explanation: text("Формат 2:1 — панорамный.", "2:1 is panoramic."),
      imageSrc: commons("Bridge Vittorio Emanuele II at sunset.jpg"),
      imageAlt: text("Мост на закате", "Bridge at sunset"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[2/1]",
      imageClass: "object-cover",
      options: [
        { label: "2:1" },
        { label: "16:9" },
        { label: "3:2" },
        { label: "4:3" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-5-4",
      prompt: text("Определи формат изображения.", "Identify the image aspect ratio."),
      helper: text("Кадр чуть выше, чем 4:3.", "The frame is slightly taller than 4:3."),
      explanation: text("Формат 5:4 — почти квадратный.", "5:4 is almost square."),
      imageSrc: commons("Lake Agnes im Banff National Park.jpg"),
      imageAlt: text("Озеро", "Lake"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[5/4]",
      imageClass: "object-cover",
      options: [
        { label: "5:4" },
        { label: "4:3" },
        { label: "1:1" },
        { label: "3:2" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-3-4",
      prompt: text("Какой формат кадра?", "What is the frame aspect ratio?"),
      helper: text("Кадр вертикальный.", "The frame is vertical."),
      explanation: text("Формат 3:4 — портретный.", "3:4 is a portrait ratio."),
      imageSrc: commons("Girl_with_a_Pearl_Earring.jpg"),
      imageAlt: text("Портрет", "Portrait"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[3/4]",
      imageClass: "object-contain",
      options: [
        { label: "3:4" },
        { label: "2:3" },
        { label: "4:3" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-2-3",
      prompt: text("Определи формат кадра.", "Identify the frame aspect ratio."),
      helper: text("Высота значительно больше ширины.", "Height is much greater than width."),
      explanation: text("Формат 2:3 — классический портрет.", "2:3 is a classic portrait ratio."),
      imageSrc: commons("Mountains from Hatcher Pass (Alaska).jpg"),
      imageAlt: text("Горы", "Mountains"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[2/3]",
      imageClass: "object-cover",
      options: [
        { label: "2:3" },
        { label: "3:4" },
        { label: "4:3" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-9-16",
      prompt: text("Определи формат изображения.", "Identify the image aspect ratio."),
      helper: text("Вертикальный кадр, как в мобильном.", "Vertical frame, like on mobile."),
      explanation: text("Это формат 9:16.", "This is 9:16."),
      imageSrc: commons("Forest road Slavne 2017 G8.jpg"),
      imageAlt: text("Лесная дорога", "Forest road"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[9/16]",
      imageClass: "object-cover",
      options: [
        { label: "9:16" },
        { label: "2:3" },
        { label: "3:4" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-21-9",
      prompt: text("Какой формат кадра?", "What is the frame aspect ratio?"),
      helper: text("Очень широкий кадр, почти панорама.", "Very wide frame, almost panoramic."),
      explanation: text("Формат 21:9 — ультраширокий.", "21:9 is ultra-wide."),
      imageSrc: commons("River Narmada from Maheshwar Fort.jpg"),
      imageAlt: text("Река", "River"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[21/9]",
      imageClass: "object-cover",
      options: [
        { label: "21:9" },
        { label: "16:9" },
        { label: "3:2" },
        { label: "2:1" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "format-4-5",
      prompt: text("Определи формат изображения.", "Identify the image aspect ratio."),
      helper: text("Высота немного больше ширины.", "Height is slightly greater than width."),
      explanation: text("Формат 4:5 часто используется в соцсетях.", "4:5 is common on social media."),
      imageSrc: commons("Beach - San Agustín.jpg"),
      imageAlt: text("Пляж", "Beach"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-md aspect-[4/5]",
      imageClass: "object-cover",
      options: [
        { label: "4:5" },
        { label: "3:4" },
        { label: "2:3" },
        { label: "1:1" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "format-3-1",
      prompt: text("Определи формат кадра.", "Identify the frame aspect ratio."),
      helper: text("Очень широкий, почти баннер.", "Very wide, almost a banner."),
      explanation: text("Формат 3:1 — панорамный.", "3:1 is panoramic."),
      imageSrc: commons("City Skyline from Sidney Harbour.JPG"),
      imageAlt: text("Городской пейзаж", "Cityscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/1]",
      imageClass: "object-cover",
      options: [
        { label: "3:1" },
        { label: "2:1" },
        { label: "16:9" },
        { label: "3:2" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "format-5-3",
      prompt: text("Определи формат изображения.", "Identify the image aspect ratio."),
      helper: text("Широкий кадр, но не панорама.", "Wide frame but not panoramic."),
      explanation: text("Формат 5:3 — умеренно широкий.", "5:3 is moderately wide."),
      imageSrc: commons("Desert varnish - Valley of Fire State Park.JPG"),
      imageAlt: text("Пустыня", "Desert"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[5/3]",
      imageClass: "object-cover",
      options: [
        { label: "5:3" },
        { label: "3:2" },
        { label: "16:9" },
        { label: "4:3" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
  ],
  "color-eye": [
    {
      id: "color-flower",
      prompt: text("Какой цвет ближе всего к лепесткам?", "Which color is closest to the petals?"),
      helper: text("Оцени доминирующий оттенок.", "Estimate the dominant hue."),
      explanation: text(
        "Лепестки ближе к красно-коралловому оттенку.",
        "The petals are closest to a red-coral hue.",
      ),
      imageSrc: commons("Example.jpg"),
      imageAlt: text("Красный цветок", "Red flower"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "#e24b4b", color: "#e24b4b" },
        { label: "#f2c94c", color: "#f2c94c" },
        { label: "#2d9cdb", color: "#2d9cdb" },
        { label: "#27ae60", color: "#27ae60" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-sky",
      prompt: text("Какой оттенок ближе всего к небу?", "Which shade is closest to the sky?"),
      helper: text("Сравни холодные тона.", "Compare the cool tones."),
      explanation: text(
        "Небо ближе к холодному синеватому оттенку.",
        "The sky is closer to a cool bluish shade.",
      ),
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: text("Горный пейзаж", "Mountain landscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#4f7fbf", color: "#4f7fbf" },
        { label: "#5f9ea0", color: "#5f9ea0" },
        { label: "#7f8c8d", color: "#7f8c8d" },
        { label: "#6ab04c", color: "#6ab04c" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-earth",
      prompt: text("Какой цвет ближе к океанам на фото?", "Which color is closest to the oceans in the photo?"),
      helper: text("Оцени глубину синего.", "Assess the depth of blue."),
      explanation: text(
        "Океаны ближе к насыщенному синему оттенку.",
        "The oceans are closer to a saturated blue.",
      ),
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: text("Земля из космоса", "Earth from space"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "#1f5fbf", color: "#1f5fbf" },
        { label: "#3b82f6", color: "#3b82f6" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#94a3b8", color: "#94a3b8" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-sunset-amber",
      prompt: text("Какой оттенок ближе всего к небу на закате?", "Which shade is closest to the sunset sky?"),
      helper: text("Смотри на тёплые участки неба.", "Look at the warm areas of the sky."),
      explanation: text(
        "Закат даёт янтарно-оранжевый оттенок.",
        "The sunset gives an amber-orange hue.",
      ),
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: text("Закат", "Sunset"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#8b5cf6", color: "#8b5cf6" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-ocean-teal",
      prompt: text("Какой оттенок ближе к воде на снимке?", "Which shade is closest to the water in the shot?"),
      helper: text("Оцени доминирующий сине-зелёный тон.", "Assess the dominant blue-green tone."),
      explanation: text("Вода ближе к яркому бирюзово-синему.", "The water is closer to a vivid turquoise-blue."),
      imageSrc: commons("Ocean beach at low tide against the sun.jpg"),
      imageAlt: text("Океан на закате", "Ocean at sunset"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#f97316", color: "#f97316" },
        { label: "#16a34a", color: "#16a34a" },
        { label: "#9ca3af", color: "#9ca3af" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-forest-green",
      prompt: text("Какой оттенок ближе к листве в кадре?", "Which shade is closest to the foliage in the frame?"),
      helper: text("Смотри на средние зелёные тона.", "Look at mid green tones."),
      explanation: text("Листва ближе к насыщенному зелёному.", "The foliage is closer to a saturated green."),
      imageSrc: commons(
        "Beech Forest (AU), Great Otway National Park, Beauchamp Falls -- 2019 -- 1271.jpg"
      ),
      imageAlt: text("Лес", "Forest"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#2f855a", color: "#2f855a" },
        { label: "#60a5fa", color: "#60a5fa" },
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#a855f7", color: "#a855f7" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-snow-cold",
      prompt: text("Какой оттенок ближе всего к снегу?", "Which shade is closest to the snow?"),
      helper: text("Снег выглядит холодным и светлым.", "Snow looks cool and light."),
      explanation: text("Снег ближе к холодному светло-серому.", "Snow is closer to a cool light gray."),
      imageSrc: commons("Snow Scene at Shipka Pass 1.JPG"),
      imageAlt: text("Зимний пейзаж", "Winter landscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#e5e7eb", color: "#e5e7eb" },
        { label: "#fef3c7", color: "#fef3c7" },
        { label: "#93c5fd", color: "#93c5fd" },
        { label: "#94a3b8", color: "#94a3b8" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-desert-sand",
      prompt: text("Какой оттенок ближе к песку?", "Which shade is closest to the sand?"),
      helper: text("Смотри на тёплые землистые тона.", "Look at warm earthy tones."),
      explanation: text("Песок ближе к тёплому охристому.", "The sand is closer to a warm ochre."),
      imageSrc: commons("Acacia in Ein Khadra Desert Oasis 00 (87).jpg"),
      imageAlt: text("Пустыня с акацией", "Desert with acacia"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#d97706", color: "#d97706" },
        { label: "#3b82f6", color: "#3b82f6" },
        { label: "#16a34a", color: "#16a34a" },
        { label: "#64748b", color: "#64748b" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-flower-magenta",
      prompt: text("Какой цвет ближе к лепесткам?", "Which color is closest to the petals?"),
      helper: text("Учитывай насыщенный розовый оттенок.", "Account for the saturated pink hue."),
      explanation: text(
        "Лепестки ближе к насыщенному розово-магентовому.",
        "The petals are closer to a saturated pink-magenta.",
      ),
      imageSrc: commons(
        "Stargazer Lillies Lillium orientale 'Stargazer' Flower 2000px.jpg"
      ),
      imageAlt: text("Лилии", "Lilies"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "#ec4899", color: "#ec4899" },
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#22c55e", color: "#22c55e" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "color-lake-turquoise",
      prompt: text("Какой оттенок ближе к воде?", "Which shade is closest to the water?"),
      helper: text("Вода выглядит холодной и бирюзовой.", "The water looks cool and turquoise."),
      explanation: text("Оттенок воды ближе к бирюзовому.", "The water tone is closer to turquoise."),
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: text("Горное озеро", "Mountain lake"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#14b8a6", color: "#14b8a6" },
        { label: "#f97316", color: "#f97316" },
        { label: "#ef4444", color: "#ef4444" },
        { label: "#6b7280", color: "#6b7280" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-aurora-green",
      prompt: text("Какой оттенок ближе всего к сиянию?", "Which shade is closest to the aurora glow?"),
      helper: text("Смотри на основной цвет полярного сияния.", "Look at the main aurora color."),
      explanation: text("Сияние ближе к яркому зелёному.", "The glow is closer to a bright green."),
      imageSrc: commons("Virmalised 15.09.2017 - Aurora Borealis 15.09.2017 copy.jpg"),
      imageAlt: text("Полярное сияние", "Aurora borealis"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#22c55e", color: "#22c55e" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#f97316", color: "#f97316" },
        { label: "#a855f7", color: "#a855f7" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-river-blue",
      prompt: text("Какой оттенок ближе к воде в реке?", "Which shade is closest to the river water?"),
      helper: text("Смотри на холодные синие тона.", "Look at cool blue tones."),
      explanation: text("Вода ближе к прохладному голубому.", "The water is closer to a cool light blue."),
      imageSrc: commons("Rogue River Oregon USA.jpg"),
      imageAlt: text("Река", "River"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#38bdf8", color: "#38bdf8" },
        { label: "#f59e0b", color: "#f59e0b" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#9ca3af", color: "#9ca3af" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "color-sunset-pink",
      prompt: text("Какой оттенок ближе к облакам на закате?", "Which shade is closest to the sunset clouds?"),
      helper: text("Смотри на розово-лиловые тона.", "Look at pink-lilac tones."),
      explanation: text("Облака ближе к тёплому розовому.", "The clouds are closer to a warm pink."),
      imageSrc: commons("Honeymoon Bay Sunset 2.jpg"),
      imageAlt: text("Закат на море", "Sea sunset"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "#f472b6", color: "#f472b6" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#22c55e", color: "#22c55e" },
        { label: "#f59e0b", color: "#f59e0b" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "color-wheel": [
    {
      id: "wheel-complement",
      prompt: text("Найди дополнительный цвет к #3b82f6.", "Find the complementary color for #3b82f6."),
      helper: text("Дополнительный цвет находится напротив на круге.", "Complementary colors sit opposite on the wheel."),
      explanation: text(
        "Для синего #3b82f6 комплемент — насыщенный оранжевый.",
        "For blue #3b82f6, the complement is a saturated orange.",
      ),
      imageSrc: commons("Color Wheel.png"),
      imageAlt: text("Цветовой круг", "Color wheel"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#f97316", color: "#f97316" },
        { label: "#10b981", color: "#10b981" },
        { label: "#a855f7", color: "#a855f7" },
        { label: "#ef4444", color: "#ef4444" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "wheel-analog",
      prompt: text("Выбери аналоговый оттенок к #22c55e.", "Choose an analogous shade to #22c55e."),
      helper: text("Аналоговые — рядом на цветовом круге.", "Analogous colors are adjacent on the wheel."),
      explanation: text(
        "Аналоговый зелёный близок по тону и насыщенности.",
        "An analogous green is close in hue and saturation.",
      ),
      imageSrc: commons("Color Wheel.png"),
      imageAlt: text("Цветовой круг", "Color wheel"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#16a34a", color: "#16a34a" },
        { label: "#f97316", color: "#f97316" },
        { label: "#0ea5e9", color: "#0ea5e9" },
        { label: "#ef4444", color: "#ef4444" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "wheel-complement-2",
      prompt: text("Найди комплементарный цвет к #ef4444.", "Find the complementary color for #ef4444."),
      helper: text("Красный дополняется зелёным.", "Red is complemented by green."),
      explanation: text(
        "Комплементарный к красному — зелёный оттенок.",
        "The complement of red is a green shade.",
      ),
      imageSrc: commons("Color Wheel.png"),
      imageAlt: text("Цветовой круг", "Color wheel"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#22c55e", color: "#22c55e" },
        { label: "#3b82f6", color: "#3b82f6" },
        { label: "#a855f7", color: "#a855f7" },
        { label: "#f59e0b", color: "#f59e0b" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
  "film-type": [
    {
      id: "film-bw",
      prompt: text("Какой тип плёнки ближе всего по характеру изображения?", "Which film type best matches the image character?"),
      helper: text("Обрати внимание на тональность и зерно.", "Pay attention to tonality and grain."),
      explanation: text(
        "Контрастное чёрно-белое изображение похоже на классическую B/W плёнку.",
        "The high-contrast black-and-white look suggests classic B/W film.",
      ),
      imageSrc: commons("Migrant_Mother_(LOC_fsa.8b29516).jpg"),
      imageAlt: text("Портрет в чёрно-белой гамме", "Black-and-white portrait"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "Ilford HP5" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Velvia 50" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-vivid",
      prompt: text("Какой тип плёнки ближе всего к этой цветопередаче?", "Which film type best matches this color rendering?"),
      helper: text("Очень насыщенные цвета.", "Very saturated colors."),
      explanation: text(
        "Velvia известна сверхнасыщенными цветами и контрастом.",
        "Velvia is known for very saturated colors and strong contrast.",
      ),
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: text("Яркий пейзаж", "Vivid landscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Velvia 50" },
        { label: "Kodak Portra 400" },
        { label: "Ilford HP5" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-night-cinestill",
      prompt: text("Какая плёнка лучше всего передаст ночные неоновые огни?", "Which film best renders neon night lights?"),
      helper: text("Ищи киношный оттенок ночного света.", "Look for a cinematic night-light tint."),
      explanation: text(
        "Cinestill 800T рассчитана на ночные сцены с тёплыми огнями.",
        "Cinestill 800T is designed for night scenes with warm lights.",
      ),
      imageSrc: commons("Las Vegas (Nevada, USA), The Strip -- 2012 -- 6232.jpg"),
      imageAlt: text("Ночной город с неоном", "Neon night city"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Cinestill 800T" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Velvia 50" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-warm-gold",
      prompt: text("Какая плёнка даёт такую тёплую, золотистую подачу?", "Which film gives this warm, golden rendering?"),
      helper: text("Тёплые и солнечные тона.", "Warm, sunny tones."),
      explanation: text(
        "Kodak Gold известна мягкими золотистыми оттенками.",
        "Kodak Gold is known for soft golden tones.",
      ),
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: text("Тёплый закат", "Warm sunset"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Gold 200" },
        { label: "Fujifilm Pro 400H" },
        { label: "Kodak Ektar 100" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "film-pastel-400h",
      prompt: text("Какая плёнка ближе к этой пастельной цветопередаче?", "Which film matches this pastel color rendering?"),
      helper: text("Мягкие цвета и низкий контраст.", "Soft colors and low contrast."),
      explanation: text(
        "Fujifilm Pro 400H даёт пастельные, мягкие оттенки.",
        "Fujifilm Pro 400H produces pastel, soft tones.",
      ),
      imageSrc: commons("Lake Sylvester during the sunrise, Kahurangi, New Zealand.jpg"),
      imageAlt: text("Озеро на рассвете", "Lake at sunrise"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Pro 400H" },
        { label: "Fujifilm Velvia 50" },
        { label: "Kodak Ektar 100" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-ektar-mountain",
      prompt: text("Какая плёнка ближе всего к такой насыщенной палитре?", "Which film best matches this saturated palette?"),
      helper: text("Высокая насыщенность и контраст.", "High saturation and contrast."),
      explanation: text(
        "Kodak Ektar 100 известна яркими и чистыми цветами.",
        "Kodak Ektar 100 is known for bright, clean colors.",
      ),
      imageSrc: commons("Zagedan Lakes, Mountain cirque, Caucasus Mountains.jpg"),
      imageAlt: text("Горные озёра", "Mountain lakes"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Ektar 100" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Pro 400H" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "film-trix-bridge",
      prompt: text("Какой тип плёнки ближе всего по характеру контраста?", "Which film type best matches this contrast character?"),
      helper: text("Классическая чёрно-белая подача.", "Classic black-and-white rendering."),
      explanation: text(
        "Kodak Tri-X даёт контрастную чёрно-белую картинку.",
        "Kodak Tri-X gives a contrasty black-and-white look.",
      ),
      imageSrc: commons("Manhattan Bridge Construction 1909.jpg"),
      imageAlt: text("Мост, чёрно-белое фото", "Bridge, black-and-white photo"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-contain",
      options: [
        { label: "Kodak Tri-X 400" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Velvia 50" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-portra-market",
      prompt: text(
        "Какая плёнка ближе к натуральным тонам кожи и среды?",
        "Which film is closest to natural skin and environment tones?",
      ),
      helper: text("Мягкая и естественная цветопередача.", "Soft, natural color rendering."),
      explanation: text(
        "Kodak Portra 400 известна натуральными оттенками кожи.",
        "Kodak Portra 400 is known for natural skin tones.",
      ),
      imageSrc: commons("Moore Street market, Dublin.jpg"),
      imageAlt: text("Рынок на улице", "Street market"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Portra 400" },
        { label: "Kodak Ektar 100" },
        { label: "Fujifilm Velvia 50" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-velvia-snow",
      prompt: text("Какая плёнка подойдёт для ярких, контрастных пейзажей?", "Which film suits bright, contrasty landscapes?"),
      helper: text("Сильный контраст и холодные тона.", "Strong contrast and cool tones."),
      explanation: text(
        "Velvia подчёркивает контраст и насыщенность.",
        "Velvia emphasizes contrast and saturation.",
      ),
      imageSrc: commons("Mountains in snow, Mountain lake, Chola Valley, Nepal, Himalayas.jpg"),
      imageAlt: text("Горы и снег", "Mountains and snow"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Velvia 50" },
        { label: "Kodak Portra 400" },
        { label: "Fujifilm Pro 400H" },
        { label: "Kodak Gold 200" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-superia-forest",
      prompt: text("Какая плёнка ближе всего к зелёным тонам на фото?", "Which film best matches the green tones in the photo?"),
      helper: text("Зелёные выглядят холодными и сочными.", "The greens look cool and vivid."),
      explanation: text(
        "Fujifilm Superia даёт прохладные зелёные оттенки.",
        "Fujifilm Superia gives cool green tones.",
      ),
      imageSrc: commons("Spruce forest at Holma.jpg"),
      imageAlt: text("Еловый лес", "Spruce forest"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Fujifilm Superia 200" },
        { label: "Kodak Portra 400" },
        { label: "Kodak Gold 200" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "film-ektar-city",
      prompt: text("Какая плёнка подходит для яркого городского пейзажа?", "Which film suits a vivid cityscape?"),
      helper: text("Насыщенные тона и чёткие детали.", "Saturated tones and crisp detail."),
      explanation: text(
        "Kodak Ektar 100 подчёркивает насыщенность и детализацию.",
        "Kodak Ektar 100 emphasizes saturation and detail.",
      ),
      imageSrc: commons("Lower Manhattan from Jersey City July 2014 002.jpg"),
      imageAlt: text("Городской пейзаж", "Cityscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Ektar 100" },
        { label: "Fujifilm Pro 400H" },
        { label: "Kodak Portra 400" },
        { label: "Ilford HP5" },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "film-portra-coast",
      prompt: text("Какая плёнка ближе всего к мягкой тёплой подаче?", "Which film is closest to a soft warm rendering?"),
      helper: text("Естественные тона кожи и моря.", "Natural tones of skin and sea."),
      explanation: text(
        "Portra 400 сохраняет тёплую, натуральную палитру.",
        "Portra 400 preserves a warm, natural palette.",
      ),
      imageSrc: commons("Acapulco fishermen.jpg"),
      imageAlt: text("Рыбаки у моря", "Fishermen by the sea"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Kodak Portra 400" },
        { label: "Kodak Gold 200" },
        { label: "Fujifilm Velvia 50" },
        { label: "Cinestill 800T" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "composition-technique": [
    {
      id: "composition-thirds",
      prompt: text("Какой приём композиции использован?", "Which composition technique is used?"),
      helper: text("Горизонт и акценты смещены от центра.", "The horizon and focal points are off-center."),
      explanation: text("Композиция построена по правилу третей.", "The composition follows the rule of thirds."),
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: text("Горный пейзаж", "Mountain landscape"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Правило третей", "Rule of thirds") },
        { label: text("Центральная симметрия", "Central symmetry") },
        { label: text("Золотая спираль", "Golden spiral") },
        { label: text("Плоская композиция", "Flat composition") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "composition-center",
      prompt: text("Определи композиционный приём.", "Identify the composition technique."),
      helper: text("Главный объект расположен по центру.", "The main subject is centered."),
      explanation: text(
        "Это центральная композиция — объект в фокусе по оси.",
        "This is a centered composition — the subject sits on the axis.",
      ),
      imageSrc: commons("Example.jpg"),
      imageAlt: text("Цветок по центру кадра", "Flower centered in the frame"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: text("Центральная композиция", "Centered composition") },
        { label: text("Диагонали", "Diagonals") },
        { label: text("Золотое сечение", "Golden ratio") },
        { label: text("Ритмический повтор", "Rhythmic repetition") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-diagonal",
      prompt: text("Какой приём композиции здесь использован?", "Which composition technique is used here?"),
      helper: text("Главные линии идут по диагонали.", "The main lines run diagonally."),
      explanation: text("Диагональная композиция создаёт динамику.", "Diagonal composition creates dynamism."),
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: text("Земля", "Earth"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: text("Диагональная композиция", "Diagonal composition") },
        { label: text("Строгая симметрия", "Strict symmetry") },
        { label: text("Центральная композиция", "Centered composition") },
        { label: text("Ритмический повтор", "Rhythmic repetition") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-leading-lines",
      prompt: text("Определи композиционный приём.", "Identify the composition technique."),
      helper: text("Линии уводят взгляд вдаль.", "Lines lead the eye into the distance."),
      explanation: text(
        "Ведущие линии направляют внимание к главному объекту.",
        "Leading lines guide attention to the main subject.",
      ),
      imageSrc: commons("Vasco da Gama Bridge B&W (crop2).jpg"),
      imageAlt: text("Мост с перспективой", "Bridge in perspective"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Ведущие линии", "Leading lines") },
        { label: text("Центральная композиция", "Centered composition") },
        { label: text("Негативное пространство", "Negative space") },
        { label: text("Ритмический повтор", "Rhythmic repetition") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-symmetry",
      prompt: text("Какой приём композиции доминирует?", "Which composition technique dominates?"),
      helper: text("Левая и правая части сбалансированы.", "The left and right sides are balanced."),
      explanation: text("Композиция построена на симметрии.", "The composition is built on symmetry."),
      imageSrc: commons("Bridge and deck of Gullbritt.jpg"),
      imageAlt: text("Симметричный мост", "Symmetrical bridge"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Симметрия", "Symmetry") },
        { label: text("Диагонали", "Diagonals") },
        { label: text("Золотая спираль", "Golden spiral") },
        { label: text("Случайное расположение", "Random placement") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-negative-space",
      prompt: text("Какой приём композиции используется?", "Which composition technique is used?"),
      helper: text("В кадре много воздуха и пустоты.", "There is a lot of air and empty space in the frame."),
      explanation: text(
        "Негативное пространство подчёркивает главный объект.",
        "Negative space emphasizes the main subject.",
      ),
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: text("Закат с большим небом", "Sunset with a wide sky"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Негативное пространство", "Negative space") },
        { label: text("Ритмический повтор", "Rhythmic repetition") },
        { label: text("Диагональная композиция", "Diagonal composition") },
        { label: text("Симметрия", "Symmetry") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "composition-repetition",
      prompt: text("Определи композиционный приём.", "Identify the composition technique."),
      helper: text("Много повторяющихся вертикалей.", "Many repeating verticals."),
      explanation: text("Повтор элементов создаёт ритм.", "Repetition of elements creates rhythm."),
      imageSrc: commons(
        "Beech Forest (AU), Great Otway National Park, Beauchamp Falls -- 2019 -- 1271.jpg"
      ),
      imageAlt: text("Лес с повторяющимися стволами", "Forest with repeating trunks"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Ритмический повтор", "Rhythmic repetition") },
        { label: text("Центральная композиция", "Centered composition") },
        { label: text("Негативное пространство", "Negative space") },
        { label: text("Правило третей", "Rule of thirds") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-framing",
      prompt: text("Какой приём композиции заметен в кадре?", "Which composition technique is visible in the frame?"),
      helper: text("Кадр будто обрамлён природными элементами.", "The frame is naturally framed by elements."),
      explanation: text("Обрамление направляет взгляд внутрь сцены.", "Framing directs the eye into the scene."),
      imageSrc: commons(
        "Gyedong-gil street with climbing plants at golden hour in Seoul South Korea.jpg"
      ),
      imageAlt: text("Улица с зелёным обрамлением", "Street with green framing"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Обрамление", "Framing") },
        { label: text("Симметрия", "Symmetry") },
        { label: text("Диагонали", "Diagonals") },
        { label: text("Плоская композиция", "Flat composition") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-depth-layers",
      prompt: text("Какой приём композиции здесь использован?", "Which composition technique is used here?"),
      helper: text("Есть передний, средний и дальний планы.", "There are foreground, midground, and background layers."),
      explanation: text("Слои создают ощущение глубины.", "Layers create a sense of depth."),
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: text("Озеро с планами", "Lake with depth layers"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Слои и глубина", "Layers and depth") },
        { label: text("Негативное пространство", "Negative space") },
        { label: text("Плоская композиция", "Flat composition") },
        { label: text("Симметрия", "Symmetry") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-s-curve",
      prompt: text("Какой приём композиции здесь заметен?", "Which composition technique is visible here?"),
      helper: text("Линия в кадре плавно изгибается.", "The line in the frame curves smoothly."),
      explanation: text("S-образная линия ведёт взгляд и создаёт динамику.", "An S-curve leads the eye and creates dynamism."),
      imageSrc: commons("Rogue River Oregon USA.jpg"),
      imageAlt: text("Извилистая река", "Meandering river"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("S-образная линия", "S-curve") },
        { label: text("Центральная композиция", "Centered composition") },
        { label: text("Ритмический повтор", "Rhythmic repetition") },
        { label: text("Золотое сечение", "Golden ratio") },
      ],
      correctIndex: 0,
      difficulty: "hard",
    },
    {
      id: "composition-pattern",
      prompt: text("Какой приём композиции доминирует?", "Which composition technique dominates?"),
      helper: text("Повторяющиеся элементы строят узор.", "Repeating elements create a pattern."),
      explanation: text("Композиция опирается на паттерн и ритм.", "The composition relies on pattern and rhythm."),
      imageSrc: commons("Wet market in Singapore 2.jpg"),
      imageAlt: text("Рынок с повторяющимися формами", "Market with repeating forms"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Паттерн и повтор", "Pattern and repetition") },
        { label: text("Негативное пространство", "Negative space") },
        { label: text("Диагональная композиция", "Diagonal composition") },
        { label: text("Симметрия", "Symmetry") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "composition-silhouette",
      prompt: text("Какой приём композиции здесь использован?", "Which composition technique is used here?"),
      helper: text("Контраст между объектом и ярким фоном.", "Contrast between the subject and a bright background."),
      explanation: text("Силуэт подчёркивает форму и контраст.", "A silhouette emphasizes shape and contrast."),
      imageSrc: commons("Honeymoon Bay Sunset 2.jpg"),
      imageAlt: text("Закат с силуэтами", "Sunset with silhouettes"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Силуэт", "Silhouette") },
        { label: text("Обрамление", "Framing") },
        { label: text("Ритмический повтор", "Rhythmic repetition") },
        { label: text("Центральная композиция", "Centered composition") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "composition-perspective",
      prompt: text("Какой приём композиции здесь заметен?", "Which composition technique is visible here?"),
      helper: text("Глубина создаётся линиями перспективы.", "Depth is created by perspective lines."),
      explanation: text(
        "Линейная перспектива усиливает ощущение пространства.",
        "Linear perspective enhances the sense of space.",
      ),
      imageSrc: commons("NYC wideangle south from Top of the Rock.jpg"),
      imageAlt: text("Город с перспективой", "City with perspective"),
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: text("Линейная перспектива", "Linear perspective") },
        { label: text("Негативное пространство", "Negative space") },
        { label: text("Симметрия", "Symmetry") },
        { label: text("Плоская композиция", "Flat composition") },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "focal-length": [
    {
      id: "focal-portrait",
      prompt: "Какое фокусное расстояние вероятнее всего?",
      helper: "Смотри на перспективу и искажения.",
      explanation: "Портрет без сильных искажений — около 85 мм.",
      imageSrc: commons("Migrant_Mother_(LOC_fsa.8b29516).jpg"),
      imageAlt: "Портрет",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-wide",
      prompt: "Определи фокусное расстояние по перспективе.",
      helper: "Широкий угол даёт ощущение пространства.",
      explanation: "Пейзаж с выраженной перспективой чаще снимают на 24 мм.",
      imageSrc: commons("Fronalpstock_big.jpg"),
      imageAlt: "Пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "focal-normal",
      prompt: "Какое фокусное расстояние наиболее вероятно?",
      helper: "Перспектива выглядит естественной.",
      explanation: "Нормальный объектив для такой перспективы — около 50 мм.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-nyc-wide",
      prompt: "Какое фокусное расстояние вероятнее всего для такого кадра?",
      helper: "Сильная перспектива и широкий охват.",
      explanation: "Широкоугольный кадр чаще всего снимают на 24 мм.",
      imageSrc: commons("NYC wideangle south from Top of the Rock.jpg"),
      imageAlt: "Широкий городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "16 мм" },
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "medium",
    },
    {
      id: "focal-manhattan-tele",
      prompt: "Какое фокусное расстояние ближе для такого сжатого плана?",
      helper: "Перспектива выглядит чуть сжатой.",
      explanation: "Умеренно-телеобъектив около 85 мм даёт такое сжатие.",
      imageSrc: commons("Lower Manhattan from Jersey City July 2014 002.jpg"),
      imageAlt: "Городской пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-himalayas-tele",
      prompt: "Какое фокусное расстояние ближе для такого горного плана?",
      helper: "Горы выглядят приближенными и сжатыми.",
      explanation: "Телеобъектив около 135 мм сжимает перспективу.",
      imageSrc: commons("Himalayas, Ama Dablam, Nepal.jpg"),
      imageAlt: "Горы",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 3,
      difficulty: "hard",
    },
    {
      id: "focal-everest-tele",
      prompt: "Какое фокусное расстояние вероятнее всего здесь?",
      helper: "Очень сильное сжатие дальних планов.",
      explanation: "Длинный фокус порядка 200 мм сжимает перспективу.",
      imageSrc: commons("Everest, Himalayas.jpg"),
      imageAlt: "Горный хребет",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
        { label: "200 мм" },
      ],
      correctIndex: 3,
      difficulty: "hard",
    },
    {
      id: "focal-sunset-normal",
      prompt: "Какое фокусное расстояние ближе для такого кадра?",
      helper: "Перспектива выглядит естественной, без сильных искажений.",
      explanation: "Умеренно широкий объектив около 35 мм даёт такой эффект.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Закат",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "easy",
    },
    {
      id: "focal-waterfall-wide",
      prompt: "Какое фокусное расстояние ближе всего?",
      helper: "Кадр широкого пейзажа с большим охватом.",
      explanation: "Широкий угол около 24 мм подходит для таких сцен.",
      imageSrc: commons("Chamarel Falls Mauritius 2.JPG"),
      imageAlt: "Водопад",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "16 мм" },
        { label: "24 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "medium",
    },
    {
      id: "focal-market-normal",
      prompt: "Какое фокусное расстояние вероятнее всего?",
      helper: "Перспектива выглядит близкой к естественной.",
      explanation: "Около 50 мм даёт привычную перспективу.",
      imageSrc: commons("Moore Street market, Dublin.jpg"),
      imageAlt: "Уличный рынок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 2,
      difficulty: "easy",
    },
    {
      id: "focal-fishermen-portrait",
      prompt: "Какое фокусное расстояние ближе для этого плана?",
      helper: "Объект выделен, фон слегка сжат.",
      explanation: "Портретный диапазон около 85 мм подходит лучше всего.",
      imageSrc: commons("Acapulco fishermen.jpg"),
      imageAlt: "Рыбаки",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
        { label: "135 мм" },
      ],
      correctIndex: 2,
      difficulty: "medium",
    },
    {
      id: "focal-bazaar-mid",
      prompt: "Какое фокусное расстояние вероятнее всего?",
      helper: "Кадр не слишком широкий и не слишком тесный.",
      explanation: "Умеренно широкий объектив около 35 мм выглядит правдоподобно.",
      imageSrc: commons("Grand-Bazaar Shop.jpg"),
      imageAlt: "Внутри магазина",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 1,
      difficulty: "medium",
    },
    {
      id: "focal-lake-normal",
      prompt: "Какое фокусное расстояние ближе всего?",
      helper: "Перспектива спокойная и без искажений.",
      explanation: "Около 50 мм даёт естественный масштаб.",
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: "Озеро",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "24 мм" },
        { label: "35 мм" },
        { label: "50 мм" },
        { label: "85 мм" },
      ],
      correctIndex: 2,
      difficulty: "easy",
    },
  ],
  "wcag-issue": [
    {
      id: "wcag-contrast",
      prompt: text("Какая проблема доступности видна на макете?", "Which accessibility issue is visible in the layout?"),
      helper: text("Сравни контраст текста и фона.", "Compare the contrast between text and background."),
      explanation: text(
        "Текст имеет слишком низкий контраст и не проходит WCAG.",
        "The text contrast is too low and fails WCAG.",
      ),
      imageSrc: "/stock/ui-accessibility.svg",
      imageAlt: text("Макет с низким контрастом текста", "Layout with low text contrast"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Недостаточный контраст", "Insufficient contrast") },
        { label: text("Слишком мелкий кегль", "Text too small") },
        { label: text("Слабая иерархия", "Weak hierarchy") },
        { label: text("Нет отступов", "Missing spacing") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "wcag-small-text",
      prompt: text("Какая проблема доступности здесь?", "Which accessibility issue is here?"),
      helper: text("Оцени размер текста.", "Assess the text size."),
      explanation: text(
        "Текст слишком мелкий — нарушена минимальная читаемость.",
        "The text is too small and fails minimum readability.",
      ),
      imageSrc: "/stock/ui-accessibility-smalltext.svg",
      imageAlt: text("Мелкий текст", "Small text"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Слишком маленький текст", "Text too small") },
        { label: text("Низкий контраст", "Low contrast") },
        { label: text("Нет фокуса", "Missing focus") },
        { label: text("Слишком яркий фон", "Background too bright") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
  "button-color": [
    {
      id: "button-contrast",
      prompt: text("Подбери цвет кнопки с достаточным контрастом.", "Pick a button color with sufficient contrast."),
      helper: text("Кнопка должна выделяться на светлом фоне.", "The button should stand out on a light background."),
      explanation: text(
        "Насыщенный синий даёт лучший контраст и читаемость.",
        "A saturated blue offers the best contrast and readability.",
      ),
      imageSrc: "/stock/ui-button-color.svg",
      imageAlt: text("Макет с выбором цвета кнопки", "Layout with button color choices"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#1a73e8", color: "#1a73e8" },
        { label: "#9aa0a6", color: "#9aa0a6" },
        { label: "#fbbc04", color: "#fbbc04" },
        { label: "#e0e0e0", color: "#e0e0e0" },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "button-dark",
      prompt: text("Подбери контрастный цвет кнопки на тёмном фоне.", "Pick a contrasting button color on a dark background."),
      helper: text("Нужен яркий, но читаемый оттенок.", "Pick a bright yet readable hue."),
      explanation: text(
        "Светлый голубой лучше всего выделяется на тёмном фоне.",
        "Light blue stands out best on a dark background.",
      ),
      imageSrc: "/stock/ui-button-color-dark.svg",
      imageAlt: text("Тёмный экран подписки", "Dark subscription screen"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "#60a5fa", color: "#60a5fa" },
        { label: "#374151", color: "#374151" },
        { label: "#111827", color: "#111827" },
        { label: "#9ca3af", color: "#9ca3af" },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
  ],
  "font-size-choice": [
    {
      id: "font-size-ui",
      prompt: text("Какой размер основного текста здесь уместен?", "What body text size fits here?"),
      helper: text("Учти читаемость интерфейса.", "Consider UI readability."),
      explanation: text(
        "Для интерфейсов обычно выбирают 16px как базовый размер.",
        "For interfaces, 16px is a common base size.",
      ),
      imageSrc: "/stock/ui-font-size.svg",
      imageAlt: text("Макет с инструкцией", "Instruction layout"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "12 px", size: 12 },
        { label: "14 px", size: 14 },
        { label: "16 px", size: 16 },
        { label: "18 px", size: 18 },
      ],
      correctIndex: 2,
      difficulty: "easy",
    },
    {
      id: "font-size-compact",
      prompt: text("Какой размер текста поможет улучшить читаемость?", "What text size would improve readability?"),
      helper: text("Сейчас текст выглядит слишком мелким.", "The text currently looks too small."),
      explanation: text(
        "Размер 16px даёт комфортную читаемость в интерфейсе.",
        "16px provides comfortable readability in UI.",
      ),
      imageSrc: "/stock/ui-font-size-compact.svg",
      imageAlt: text("Плотный интерфейс", "Dense interface"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: "14 px", size: 14 },
        { label: "16 px", size: 16 },
        { label: "18 px", size: 18 },
        { label: "12 px", size: 12 },
      ],
      correctIndex: 1,
      difficulty: "easy",
    },
  ],
  "layout-error": [
    {
      id: "layout-error-grid",
      prompt: text("Что не так в вёрстке?", "What's wrong with the layout?"),
      helper: text("Обрати внимание на сетку карточек.", "Look at the card grid."),
      explanation: text(
        "Правая карточка смещена по вертикали — нарушена сетка.",
        "The right card is vertically misaligned, breaking the grid.",
      ),
      imageSrc: "/stock/ui-layout-error.svg",
      imageAlt: text("Макет с ошибкой в сетке", "Layout with a grid error"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Нарушено выравнивание по сетке", "Grid alignment is broken") },
        { label: text("Недостаточный контраст", "Insufficient contrast") },
        { label: text("Слишком маленькие кликабельные зоны", "Tap targets too small") },
        { label: text("Слишком много цвета", "Too much color") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "layout-error-spacing",
      prompt: text("Найди проблему в макете.", "Find the issue in the layout."),
      helper: text("Сравни вертикальные отступы.", "Compare vertical spacing."),
      explanation: text(
        "Нарушен вертикальный ритм между элементами списка.",
        "Vertical rhythm is inconsistent between list items.",
      ),
      imageSrc: "/stock/ui-layout-error-spacing.svg",
      imageAlt: text("Список с лишним отступом", "List with extra spacing"),
      imageSource: sources.internal,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2] bg-surface-2",
      imageClass: "object-contain",
      options: [
        { label: text("Нарушен вертикальный ритм", "Vertical rhythm is inconsistent") },
        { label: text("Плохой контраст", "Poor contrast") },
        { label: text("Слабая иерархия", "Weak hierarchy") },
        { label: text("Нет состояния hover", "No hover state") },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
  "palette-from-photo": [
    {
      id: "palette-flower",
      prompt: "Выбери палитру, которая ближе всего к фото.",
      helper: "Смотри на доминирующие цвета.",
      explanation: "Палитра включает красный цвет лепестков и приглушённый зелёный фон.",
      imageSrc: commons("Example.jpg"),
      imageAlt: "Цветок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "Тёплая", palette: ["#e24b4b", "#f2c94c", "#5c6b4f"] },
        { label: "Холодная", palette: ["#2d9cdb", "#6c5ce7", "#00b894"] },
        { label: "Нейтральная", palette: ["#7f8c8d", "#bdc3c7", "#ecf0f1"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-earth",
      prompt: "Какая палитра ближе всего к этому снимку?",
      helper: "Учти синие океаны и белые облака.",
      explanation: "Палитра включает насыщенный синий и светлые нейтрали.",
      imageSrc: commons("The_Earth_seen_from_Apollo_17.jpg"),
      imageAlt: "Земля из космоса",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-lg aspect-square",
      imageClass: "object-cover",
      options: [
        { label: "Небо", palette: ["#1f5fbf", "#4f7fbf", "#d9e2ec"] },
        { label: "Лес", palette: ["#166534", "#4d7c0f", "#854d0e"] },
        { label: "Тепло", palette: ["#f59e0b", "#f97316", "#ef4444"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-sunset-amber",
      prompt: "Выбери палитру, которая ближе всего к закату.",
      helper: "Тёплые оттенки неба и приглушённые тени.",
      explanation: "Палитра включает янтарные и оранжевые оттенки с тёмной тенью.",
      imageSrc: commons("Sunset 2007-1.jpg"),
      imageAlt: "Закат",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Тёплый закат", palette: ["#f59e0b", "#fb923c", "#334155"] },
        { label: "Холодный", palette: ["#0ea5e9", "#1d4ed8", "#0f172a"] },
        { label: "Зелёный", palette: ["#22c55e", "#15803d", "#065f46"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-ocean-coast",
      prompt: "Какая палитра ближе всего к морскому берегу?",
      helper: "Ищи голубые и бирюзовые оттенки.",
      explanation: "Палитра сочетает голубой, бирюзу и светлый песок.",
      imageSrc: commons("Ocean beach at low tide against the sun.jpg"),
      imageAlt: "Берег океана",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Берег", palette: ["#0ea5e9", "#14b8a6", "#f8fafc"] },
        { label: "Пустыня", palette: ["#d97706", "#f59e0b", "#78350f"] },
        { label: "Город", palette: ["#475569", "#94a3b8", "#e2e8f0"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-forest-deep",
      prompt: "Выбери палитру, которая ближе всего к лесу.",
      helper: "Обрати внимание на тёмные зелёные и коричневые.",
      explanation: "Палитра сочетает глубокий зелёный и землистые тона.",
      imageSrc: commons(
        "Beech Forest (AU), Great Otway National Park, Beauchamp Falls -- 2019 -- 1271.jpg"
      ),
      imageAlt: "Лес",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Лес", palette: ["#2f855a", "#4b5563", "#7c6f57"] },
        { label: "Закат", palette: ["#f59e0b", "#ef4444", "#1f2937"] },
        { label: "Океан", palette: ["#0ea5e9", "#0369a1", "#f8fafc"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-desert-oasis",
      prompt: "Какая палитра ближе всего к пустынному пейзажу?",
      helper: "Смотри на тёплые песочные оттенки.",
      explanation: "Палитра строится вокруг охры и тёмных теней.",
      imageSrc: commons("Acacia in Ein Khadra Desert Oasis 00 (87).jpg"),
      imageAlt: "Пустыня",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Песок", palette: ["#d97706", "#f59e0b", "#475569"] },
        { label: "Лес", palette: ["#22c55e", "#166534", "#14532d"] },
        { label: "Ночь", palette: ["#0f172a", "#1e293b", "#334155"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-aurora",
      prompt: "Какая палитра ближе всего к полярному сиянию?",
      helper: "Зелёное сияние на тёмном небе.",
      explanation: "Палитра сочетает зелёный неон и глубокий синий.",
      imageSrc: commons("Virmalised 15.09.2017 - Aurora Borealis 15.09.2017 copy.jpg"),
      imageAlt: "Полярное сияние",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Сияние", palette: ["#22c55e", "#0ea5e9", "#0f172a"] },
        { label: "Осень", palette: ["#f97316", "#b45309", "#7c2d12"] },
        { label: "Пастель", palette: ["#f9a8d4", "#93c5fd", "#e2e8f0"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-lake-turquoise",
      prompt: "Выбери палитру, которая ближе всего к горному озеру.",
      helper: "Вода выглядит холодной и бирюзовой.",
      explanation: "Палитра состоит из бирюзы, холодного синего и серых скал.",
      imageSrc: commons("Kaindy lake south-east Kazakhstan.jpg"),
      imageAlt: "Горное озеро",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Озеро", palette: ["#14b8a6", "#0ea5e9", "#94a3b8"] },
        { label: "Пустыня", palette: ["#f59e0b", "#d97706", "#78350f"] },
        { label: "Лес", palette: ["#22c55e", "#15803d", "#065f46"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-flower-pink",
      prompt: "Какая палитра ближе всего к цветку?",
      helper: "Смотри на розовые и светлые оттенки.",
      explanation: "Палитра включает розовый и светлые нейтрали.",
      imageSrc: commons(
        "Stargazer Lillies Lillium orientale 'Stargazer' Flower 2000px.jpg"
      ),
      imageAlt: "Розовые цветы",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-xl aspect-[4/3]",
      imageClass: "object-cover",
      options: [
        { label: "Цветок", palette: ["#ec4899", "#f9a8d4", "#f8fafc"] },
        { label: "Ночь", palette: ["#0f172a", "#1e293b", "#334155"] },
        { label: "Лес", palette: ["#22c55e", "#166534", "#14532d"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
    {
      id: "palette-market-warm",
      prompt: "Выбери палитру, которая ближе всего к рынку.",
      helper: "Ищи тёплые, насыщенные цвета.",
      explanation: "Палитра строится на тёплых охристых оттенках.",
      imageSrc: commons("Grand-Bazaar Shop.jpg"),
      imageAlt: "Рынок",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Тёплая", palette: ["#b45309", "#f59e0b", "#7c2d12"] },
        { label: "Холодная", palette: ["#0ea5e9", "#1d4ed8", "#0f172a"] },
        { label: "Пастель", palette: ["#f9a8d4", "#93c5fd", "#e2e8f0"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-night-city",
      prompt: "Какая палитра ближе всего к ночному городу?",
      helper: "Неоновые акценты на тёмном фоне.",
      explanation: "Палитра сочетает холодный синий, тёплый неон и фиолетовый.",
      imageSrc: commons("Las Vegas (Nevada, USA), The Strip -- 2012 -- 6232.jpg"),
      imageAlt: "Ночной город",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Неон", palette: ["#0ea5e9", "#f97316", "#a855f7"] },
        { label: "Монохром", palette: ["#334155", "#64748b", "#e2e8f0"] },
        { label: "Лес", palette: ["#22c55e", "#15803d", "#065f46"] },
      ],
      correctIndex: 0,
      difficulty: "medium",
    },
    {
      id: "palette-snow-blue",
      prompt: "Какая палитра ближе всего к зимнему пейзажу?",
      helper: "Снег и холодные тени.",
      explanation: "Палитра включает холодный белый, голубой и серый.",
      imageSrc: commons("Snow Scene at Shipka Pass 1.JPG"),
      imageAlt: "Зимний пейзаж",
      imageSource: sources.commons,
      imageFrameClass: "w-full max-w-2xl aspect-[3/2]",
      imageClass: "object-cover",
      options: [
        { label: "Зима", palette: ["#e5e7eb", "#93c5fd", "#64748b"] },
        { label: "Осень", palette: ["#f59e0b", "#d97706", "#78350f"] },
        { label: "Тропики", palette: ["#22c55e", "#14b8a6", "#0ea5e9"] },
      ],
      correctIndex: 0,
      difficulty: "easy",
    },
  ],
};
